name: Build and Submit IOS App

on:
  push:
    branches: [main]

jobs:
  build_ios:
    name: Build IOS App Binary
    type: build
    params:
      platform: ios
      profile: production
  submit_ios_app:
    name: Submit to App Stores
    type: submit
    needs: [build_ios]
    env:
      EXPO_DEBUG: "1"
    params:
      platform: ios
      build_id: ${{ needs.build_ios.outputs.build_id }}
      profile: production
  notification_teams:
    name: Notify Microsoft Teams
    type: custom
    needs: [submit_ios_app]

    steps:
      - name: Send status to Teams
        env:
          TEAMS_WEBHOOK_URL: "https://defaultaa988e77b0e34f06aabede25235728.77.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/096e911d604d4dd888079d793342333c/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=KzG5jznBNR16wX9Xem3NYI9_T25_Q7reFftMPTsbvHE"
          APP_VERSION: ${{ needs.build_ios.outputs.app_version }}
          BUILD_NUMBER: ${{ needs.build_ios.outputs.app_build_version }}
        run: |
          curl -H "Content-Type: application/json" -d "{
              \"type\": \"message\",
              \"attachments\": [
                  {
                      \"contentType\": \"application/vnd.microsoft.card.adaptive\",
                      \"content\": {
                          \"type\": \"AdaptiveCard\",
                          \"body\": [
                              {
                                  \"type\": \"TextBlock\",
                                  \"text\": \"LegalSynqV3 Production Build\",
                                  \"weight\": \"bolder\",
                                  \"size\": \"medium\"
                              },
                              {
                                  \"type\": \"FactSet\",
                                  \"facts\": [
                                      {\"title\": \"Workflow:\", \"value\": \"Build and Submit Production IOS App\"},
                                      {\"title\": \"Platform:\", \"value\": \"iOS\"},
                                      {\"title\": \"Profile:\", \"value\": \"Production\"},
                                      {\"title\": \"App Version:\", \"value\": \"$APP_VERSION\"},
                                      {\"title\": \"Build Number:\", \"value\": \"$BUILD_NUMBER\"}
                                  ]
                              }
                          ],
                          \"\$schema\": \"http://adaptivecards.io\",
                          \"version\": \"1.2\"
                      }
                  }
              ]
          }" $TEAMS_WEBHOOK_URL