name: Build and Submit QA IOS App

on:
  push:
    branches: [main]

jobs:
  build_ios:
    name: Build QA IOS App Binary
    type: build
    params:
      platform: ios
      profile: qa
  submit_ios_app:
    name: Submit QA Build to App Stores
    type: submit
    needs: [build_ios]
    env:
      EXPO_DEBUG: "1"
    params:
      platform: ios
      build_id: ${{ needs.build_ios.outputs.build_id }}
      profile: qa
