using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;
using Liens.Api.HostedServices;
using Liens.Api.Tests.Helpers;
using Liens.Domain.Entities;
using Liens.Infrastructure.Persistence;
using Liens.Infrastructure.Services;
using Microsoft.Extensions.DependencyInjection;

namespace Liens.Api.Tests.Tests;

public sealed class AutoGeneratedReportEndpointTests : IClassFixture<LiensApiFactory>, IAsyncLifetime
{
    private readonly LiensApiFactory _factory;
    private HttpClient _client = null!;

    public AutoGeneratedReportEndpointTests(LiensApiFactory factory) => _factory = factory;

    public async Task InitializeAsync()
    {
        using var scope = _factory.Services.CreateScope();
        await SeedHelper.SeedAsync(scope.ServiceProvider);

        _client = _factory.CreateClient();
        _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(
            "Bearer",
            JwtTokenHelper.CreateFullAccessToken(SeedHelper.TenantId, SeedHelper.UserId));
    }

    public Task DisposeAsync() => Task.CompletedTask;

    [Fact]
    public async Task List_is_tenant_scoped_ordered_and_paginated()
    {
        await AddReportAsync(SeedHelper.TenantId, new DateOnly(2026, 8, 3));
        await AddReportAsync(SeedHelper.TenantId, new DateOnly(2026, 8, 10));
        await AddReportAsync(SeedHelper.TenantId, new DateOnly(2026, 8, 17));
        await AddReportAsync(Guid.Parse("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"), new DateOnly(2026, 8, 24));

        var response = await _client.GetAsync(
            "/api/liens/reports/auto-generated?page=1&pageSize=2");

        response.StatusCode.Should().Be(HttpStatusCode.OK);
        response.Headers.CacheControl?.NoStore.Should().BeTrue();
        var document = await response.Content.ReadFromJsonAsync<JsonDocument>();
        var root = document!.RootElement;
        root.GetProperty("totalCount").GetInt32().Should().Be(3);
        root.GetProperty("page").GetInt32().Should().Be(1);
        root.GetProperty("pageSize").GetInt32().Should().Be(2);
        root.GetProperty("data").GetArrayLength().Should().Be(2);
        root.GetProperty("data")[0].GetProperty("date").GetString().Should().Be("2026-08-17");
        root.GetProperty("data")[0].GetProperty("tenantId").GetGuid().Should().Be(SeedHelper.TenantId);
    }

    [Theory]
    [InlineData(0, 10)]
    [InlineData(1, 0)]
    [InlineData(1, 101)]
    public async Task List_rejects_invalid_pagination(int page, int pageSize)
    {
        var response = await _client.GetAsync(
            $"/report/auto-generated?page={page}&pageSize={pageSize}");

        response.StatusCode.Should().Be(HttpStatusCode.BadRequest);
        response.Headers.CacheControl?.NoStore.Should().BeTrue();
    }

    [Fact]
    public async Task List_requires_authentication_and_case_read_permission()
    {
        using var anonymous = _factory.CreateClient();
        var unauthenticated = await anonymous.GetAsync("/report/auto-generated");
        unauthenticated.StatusCode.Should().Be(HttpStatusCode.Unauthorized);

        _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(
            "Bearer",
            JwtTokenHelper.CreateToken(SeedHelper.TenantId, SeedHelper.UserId, []));
        var forbidden = await _client.GetAsync("/report/auto-generated");
        forbidden.StatusCode.Should().Be(HttpStatusCode.Forbidden);
    }

    [Fact]
    public async Task Execute_uses_stored_date_and_returns_weekly_bcc_envelope()
    {
        var report = await AddReportAsync(SeedHelper.TenantId, new DateOnly(2026, 8, 17));

        var response = await _client.PostAsync(
            $"/api/liens/reports/auto-generated/{report.Id}/execute",
            content: null);

        response.StatusCode.Should().Be(HttpStatusCode.OK);
        response.Headers.CacheControl?.NoStore.Should().BeTrue();
        var document = await response.Content.ReadFromJsonAsync<JsonDocument>();
        var root = document!.RootElement;
        root.GetProperty("asOfDate").GetString().Should().Be("2026-08-17");
        root.GetProperty("report").GetProperty("reportId").GetInt64().Should().Be(report.Id);
        root.GetProperty("totalCount").GetInt32().Should().Be(0);
    }

    [Fact]
    public async Task Execute_returns_not_found_for_cross_tenant_report()
    {
        var report = await AddReportAsync(SeedHelper.TenantId, new DateOnly(2026, 8, 17));
        var otherTenantId = Guid.Parse("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa");
        _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(
            "Bearer",
            JwtTokenHelper.CreateFullAccessToken(otherTenantId, SeedHelper.UserId));

        var response = await _client.PostAsync(
            $"/report/auto-generated/{report.Id}/execute",
            content: null);

        response.StatusCode.Should().Be(HttpStatusCode.NotFound);
    }

    [Fact]
    public async Task Execute_rejects_unregistered_api_path()
    {
        var report = await AddReportAsync(
            SeedHelper.TenantId,
            new DateOnly(2026, 8, 17),
            "/not/allowed");

        var response = await _client.PostAsync(
            $"/report/auto-generated/{report.Id}/execute",
            content: null);

        response.StatusCode.Should().Be(HttpStatusCode.Conflict);
    }

    [Theory]
    [InlineData("/api/liens/reports/weekly-bcc", true)]
    [InlineData("/report/weekly-bcc", true)]
    [InlineData("/report/weekly-bcc/", false)]
    [InlineData("https://example.test/report/weekly-bcc", false)]
    public void Dispatcher_supports_only_exact_registered_paths(string path, bool expected)
    {
        var dispatcher = new AutoGeneratedReportDispatcher(null!);
        dispatcher.Supports(path).Should().Be(expected);
    }

    [Fact]
    public void Scheduler_uses_friday_four_am_across_pst_and_pdt()
    {
        var pacific = WeeklyAutoGeneratedReportHostedService.ResolvePacificTimeZone();

        WeeklyAutoGeneratedReportHostedService.GetLatestDueReportDate(
                new DateTimeOffset(2026, 1, 9, 11, 59, 59, TimeSpan.Zero),
                pacific)
            .Should().Be(new DateOnly(2026, 1, 2));
        WeeklyAutoGeneratedReportHostedService.GetLatestDueReportDate(
                new DateTimeOffset(2026, 1, 9, 12, 0, 0, TimeSpan.Zero),
                pacific)
            .Should().Be(new DateOnly(2026, 1, 9));
        WeeklyAutoGeneratedReportHostedService.GetLatestDueReportDate(
                new DateTimeOffset(2026, 8, 21, 11, 0, 0, TimeSpan.Zero),
                pacific)
            .Should().Be(new DateOnly(2026, 8, 21));
    }

    [Fact]
    public void Scheduler_calculates_exact_next_occurrence()
    {
        var pacific = WeeklyAutoGeneratedReportHostedService.ResolvePacificTimeZone();
        var beforeSummerDue = new DateTimeOffset(2026, 8, 21, 10, 59, 0, TimeSpan.Zero);

        WeeklyAutoGeneratedReportHostedService.GetNextOccurrence(beforeSummerDue, pacific)
            .Should().Be(new DateTimeOffset(2026, 8, 21, 11, 0, 0, TimeSpan.Zero));
    }

    private async Task<AutoGeneratedReport> AddReportAsync(
        Guid tenantId,
        DateOnly reportDate,
        string apiPath = AutoGeneratedReportDispatcher.CanonicalWeeklyBccPath)
    {
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<LiensDbContext>();
        var report = AutoGeneratedReport.Create(
            tenantId,
            $"weekly_bcc_{reportDate:yyyy-MM-dd}",
            $"Weekly BCC - {reportDate:MM/dd/yyyy}",
            reportDate,
            DateTime.UtcNow,
            apiPath);
        db.AutoGeneratedReports.Add(report);
        await db.SaveChangesAsync();
        return report;
    }
}
