using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using Liens.Api.HostedServices;
using Liens.Api.Tests.Helpers;
using Liens.Application.DTOs;
using Liens.Application.Interfaces;
using Liens.Application.Repositories;
using Liens.Domain.Entities;
using Liens.Domain.Enums;
using Liens.Infrastructure.Persistence;
using Liens.Infrastructure.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging.Abstractions;

namespace Liens.Api.Tests.Tests;

public sealed class AutoGeneratedReportEndpointTests : IClassFixture<LiensApiFactory>, IAsyncLifetime
{
    private readonly LiensApiFactory _factory;
    private HttpClient _client = null!;

    public AutoGeneratedReportEndpointTests(LiensApiFactory factory) => _factory = factory;

    public async Task InitializeAsync()
    {
        using var scope = _factory.Services.CreateScope();
        await SeedHelper.SeedAsync(scope.ServiceProvider);

        _client = _factory.CreateClient();
        _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(
            "Bearer",
            JwtTokenHelper.CreateFullAccessToken(SeedHelper.TenantId, SeedHelper.UserId));
    }

    public Task DisposeAsync() => Task.CompletedTask;

    [Fact]
    public async Task List_is_tenant_scoped_ordered_and_paginated()
    {
        await AddReportAsync(SeedHelper.TenantId, new DateOnly(2026, 8, 3));
        await AddReportAsync(SeedHelper.TenantId, new DateOnly(2026, 8, 10));
        await AddReportAsync(SeedHelper.TenantId, new DateOnly(2026, 8, 17));
        await AddReportAsync(Guid.Parse("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"), new DateOnly(2026, 8, 24));

        var response = await _client.GetAsync(
            "/api/liens/reports/auto-generated?page=1&pageSize=2");

        response.StatusCode.Should().Be(HttpStatusCode.OK);
        response.Headers.CacheControl?.NoStore.Should().BeTrue();
        var document = await response.Content.ReadFromJsonAsync<JsonDocument>();
        var root = document!.RootElement;
        root.GetProperty("totalCount").GetInt32().Should().Be(3);
        root.GetProperty("page").GetInt32().Should().Be(1);
        root.GetProperty("pageSize").GetInt32().Should().Be(2);
        root.GetProperty("data").GetArrayLength().Should().Be(2);
        root.GetProperty("data")[0].GetProperty("date").GetString().Should().Be("2026-08-17");
        root.GetProperty("data")[0].GetProperty("tenantId").GetGuid().Should().Be(SeedHelper.TenantId);
        root.GetProperty("data")[0].TryGetProperty("columns", out _).Should().BeFalse();
    }

    [Theory]
    [InlineData(0, 10)]
    [InlineData(1, 0)]
    [InlineData(1, 101)]
    public async Task List_rejects_invalid_pagination(int page, int pageSize)
    {
        var response = await _client.GetAsync(
            $"/report/auto-generated?page={page}&pageSize={pageSize}");

        response.StatusCode.Should().Be(HttpStatusCode.BadRequest);
        response.Headers.CacheControl?.NoStore.Should().BeTrue();
    }

    [Fact]
    public async Task List_requires_authentication_and_case_read_permission()
    {
        using var anonymous = _factory.CreateClient();
        var unauthenticated = await anonymous.GetAsync("/report/auto-generated");
        unauthenticated.StatusCode.Should().Be(HttpStatusCode.Unauthorized);

        _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(
            "Bearer",
            JwtTokenHelper.CreateToken(SeedHelper.TenantId, SeedHelper.UserId, []));
        var forbidden = await _client.GetAsync("/report/auto-generated");
        forbidden.StatusCode.Should().Be(HttpStatusCode.Forbidden);
    }

    [Fact]
    public async Task Execute_uses_stored_date_and_returns_weekly_bcc_envelope()
    {
        var report = await AddReportAsync(SeedHelper.TenantId, new DateOnly(2026, 8, 17));

        var response = await _client.PostAsync(
            $"/api/liens/reports/auto-generated/{report.Id}/execute",
            content: null);

        response.StatusCode.Should().Be(HttpStatusCode.OK);
        response.Headers.CacheControl?.NoStore.Should().BeTrue();
        var document = await response.Content.ReadFromJsonAsync<JsonDocument>();
        var root = document!.RootElement;
        root.GetProperty("asOfDate").GetString().Should().Be("2026-08-17");
        root.GetProperty("report").GetProperty("reportId").GetInt64().Should().Be(report.Id);
        root.GetProperty("totalCount").GetInt32().Should().Be(0);
        root.GetProperty("page").GetInt32().Should().Be(1);
        root.GetProperty("pageSize").GetInt32().Should().Be(50);
        root.GetProperty("totalPages").GetInt32().Should().Be(0);
        root.GetProperty("reportType").GetString().Should().Be("WEEKLY_BCC");
        root.GetProperty("schemaVersion").GetInt32().Should().Be(1);
        root.GetProperty("columns").GetArrayLength().Should().Be(57);
        root.GetProperty("columns")[9].GetProperty("key").GetString().Should().Be("caseId");
        root.GetProperty("columns")[9].GetProperty("label").GetString().Should().Be("Case ID");
        root.GetProperty("columns")[9].GetProperty("index").GetInt32().Should().Be(9);
        root.GetProperty("columns")[33].GetProperty("key").GetString().Should().Be("noted");
        root.GetProperty("columns")[33].GetProperty("label").GetString().Should().Be("Notes");
        root.GetProperty("data").GetArrayLength().Should().Be(0);
    }

    [Fact]
    public async Task Execute_pages_in_database_and_returns_columns_aligned_with_rows()
    {
        var report = await AddReportAsync(SeedHelper.TenantId, new DateOnly(2026, 8, 17));
        await AddWeeklyBccLiensAsync(
            ("LIEN-PAGE-001", new DateOnly(2026, 8, 1)),
            ("LIEN-PAGE-002", new DateOnly(2026, 8, 2)),
            ("LIEN-PAGE-003", new DateOnly(2026, 8, 3)));

        var response = await _client.PostAsync(
            $"/api/liens/reports/auto-generated/{report.Id}/execute?page=2&pageSize=2",
            content: null);

        response.StatusCode.Should().Be(HttpStatusCode.OK);
        var document = await response.Content.ReadFromJsonAsync<JsonDocument>();
        var root = document!.RootElement;
        root.GetProperty("page").GetInt32().Should().Be(2);
        root.GetProperty("pageSize").GetInt32().Should().Be(2);
        root.GetProperty("totalPages").GetInt32().Should().Be(2);
        root.GetProperty("totalCount").GetInt32().Should().Be(3);
        root.GetProperty("data").GetArrayLength().Should().Be(1);
        root.GetProperty("data")[0].GetProperty("lienId").GetString().Should().Be("LIEN-PAGE-003");

        var summary = root.GetProperty("summaryTotals");
        summary.GetProperty("totalCases").GetInt32().Should().Be(1);
        summary.GetProperty("totalOpenCases").GetInt32().Should().Be(1);
        summary.GetProperty("totalClosedCases").GetInt32().Should().Be(0);
        summary.GetProperty("totalLiens").GetInt32().Should().Be(3);
        summary.GetProperty("totalOpenLiens").GetInt32().Should().Be(3);
        summary.GetProperty("totalPurchaseAmt").GetDecimal().Should().Be(0m);
        summary.GetProperty("totalReturnedAmt").GetDecimal().Should().Be(0m);
        summary.GetProperty("totalBillingAmt").GetDecimal().Should().Be(300m);

        var columns = root.GetProperty("columns").EnumerateArray().ToArray();
        columns.Should().HaveCount(57);
        columns.Select(column => column.GetProperty("index").GetInt32())
            .Should().Equal(Enumerable.Range(0, 57));
        columns.Select(column => column.GetProperty("key").GetString())
            .Should().OnlyHaveUniqueItems();
        columns.Select(column => column.GetProperty("key").GetString())
            .Should().Equal(root.GetProperty("data")[0]
                .EnumerateObject()
                .Select(property => property.Name));
    }

    [Fact]
    public async Task Execute_returns_empty_data_for_out_of_range_page_with_full_count_and_columns()
    {
        var report = await AddReportAsync(SeedHelper.TenantId, new DateOnly(2026, 8, 17));
        await AddWeeklyBccLiensAsync(("LIEN-PAGE-OUT", new DateOnly(2026, 8, 1)));

        var response = await _client.PostAsync(
            $"/report/auto-generated/{report.Id}/execute?page=4&pageSize=2",
            content: null);

        response.StatusCode.Should().Be(HttpStatusCode.OK);
        var document = await response.Content.ReadFromJsonAsync<JsonDocument>();
        var root = document!.RootElement;
        root.GetProperty("page").GetInt32().Should().Be(4);
        root.GetProperty("totalPages").GetInt32().Should().Be(1);
        root.GetProperty("totalCount").GetInt32().Should().Be(1);
        root.GetProperty("columns").GetArrayLength().Should().Be(57);
        root.GetProperty("data").GetArrayLength().Should().Be(0);
    }

    [Theory]
    [InlineData(0, 10)]
    [InlineData(1, 0)]
    [InlineData(1, 101)]
    public async Task Execute_rejects_invalid_pagination(int page, int pageSize)
    {
        var report = await AddReportAsync(SeedHelper.TenantId, new DateOnly(2026, 8, 17));

        var response = await _client.PostAsync(
            $"/api/liens/reports/auto-generated/{report.Id}/execute?page={page}&pageSize={pageSize}",
            content: null);

        response.StatusCode.Should().Be(HttpStatusCode.BadRequest);
        response.Headers.CacheControl?.NoStore.Should().BeTrue();
    }

    [Fact]
    public async Task Execute_canonical_and_legacy_routes_return_identical_definitions()
    {
        var report = await AddReportAsync(SeedHelper.TenantId, new DateOnly(2026, 8, 17));

        var canonical = await _client.PostAsync(
            $"/api/liens/reports/auto-generated/{report.Id}/execute?page=1&pageSize=10",
            content: null);
        var legacy = await _client.PostAsync(
            $"/report/auto-generated/{report.Id}/execute?page=1&pageSize=10",
            content: null);

        var canonicalDocument = await canonical.Content.ReadFromJsonAsync<JsonDocument>();
        var legacyDocument = await legacy.Content.ReadFromJsonAsync<JsonDocument>();
        canonicalDocument!.RootElement.GetProperty("reportType").GetString()
            .Should().Be(legacyDocument!.RootElement.GetProperty("reportType").GetString());
        canonicalDocument.RootElement.GetProperty("schemaVersion").GetInt32()
            .Should().Be(legacyDocument.RootElement.GetProperty("schemaVersion").GetInt32());
        canonicalDocument.RootElement.GetProperty("columns").GetRawText()
            .Should().Be(legacyDocument.RootElement.GetProperty("columns").GetRawText());
    }

    [Fact]
    public async Task Export_returns_all_rows_in_column_order_with_formula_safe_csv()
    {
        var report = await AddReportAsync(SeedHelper.TenantId, new DateOnly(2026, 8, 17));
        await AddWeeklyBccLiensAsync(
            ("=2+2", new DateOnly(2026, 8, 1)),
            ("LIEN,\"Q\"", new DateOnly(2026, 8, 2)),
            ("LIEN-Ñ-003", new DateOnly(2026, 8, 3)));

        var canonical = await _client.PostAsync(
            $"/api/liens/reports/auto-generated/{report.Id}/export",
            content: null);
        var legacy = await _client.PostAsync(
            $"/report/auto-generated/{report.Id}/export",
            content: null);

        canonical.StatusCode.Should().Be(HttpStatusCode.OK);
        canonical.Headers.CacheControl?.NoStore.Should().BeTrue();
        var canonicalDocument = await canonical.Content.ReadFromJsonAsync<JsonDocument>();
        var legacyDocument = await legacy.Content.ReadFromJsonAsync<JsonDocument>();
        var item = canonicalDocument!.RootElement.GetProperty("data")[0];
        item.GetProperty("filename").GetString().Should().Be("weekly_bcc_20260817.csv");
        item.GetProperty("export_format").GetString().Should().Be("csv");
        item.GetProperty("base64").GetString()
            .Should().Be(legacyDocument!.RootElement.GetProperty("data")[0].GetProperty("base64").GetString());

        var csv = Encoding.UTF8.GetString(Convert.FromBase64String(item.GetProperty("base64").GetString()!));
        var lines = csv.Split("\r\n", StringSplitOptions.None);
        lines[0].Split(',').Should().HaveCount(57);
        lines[0].Should().StartWith("Plaintiff First Name,Plaintiff Last Name,Plaintiff Date of Birth");
        lines[0].Split(',')[33].Should().Be("Notes");
        lines.Should().HaveCount(5);
        csv.Should().Contain("'=2+2");
        csv.Should().Contain("\"LIEN,\"\"Q\"\"\"");
        csv.Should().Contain("LIEN-Ñ-003");
    }

    [Fact]
    public async Task Export_preserves_not_found_and_unsupported_path_behavior()
    {
        var unsupported = await AddReportAsync(
            SeedHelper.TenantId,
            new DateOnly(2026, 8, 17),
            "/not/allowed");

        var unsupportedResponse = await _client.PostAsync(
            $"/api/liens/reports/auto-generated/{unsupported.Id}/export",
            content: null);
        unsupportedResponse.StatusCode.Should().Be(HttpStatusCode.Conflict);

        var otherTenantId = Guid.Parse("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa");
        _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(
            "Bearer",
            JwtTokenHelper.CreateFullAccessToken(otherTenantId, SeedHelper.UserId));
        var crossTenantResponse = await _client.PostAsync(
            $"/report/auto-generated/{unsupported.Id}/export",
            content: null);
        crossTenantResponse.StatusCode.Should().Be(HttpStatusCode.NotFound);
    }

    [Fact]
    public async Task Export_includes_rows_beyond_the_internal_batch_size()
    {
        var report = await AddReportAsync(SeedHelper.TenantId, new DateOnly(2026, 8, 17));
        var rows = Enumerable.Range(0, 101)
            .Select(index => ($"LIEN-BATCH-{index:D3}", new DateOnly(2026, 8, 1)))
            .ToArray();
        await AddWeeklyBccLiensAsync(rows);

        var response = await _client.PostAsync(
            $"/api/liens/reports/auto-generated/{report.Id}/export",
            content: null);

        response.StatusCode.Should().Be(HttpStatusCode.OK);
        var document = await response.Content.ReadFromJsonAsync<JsonDocument>();
        var base64 = document!.RootElement.GetProperty("data")[0].GetProperty("base64").GetString()!;
        var csv = Encoding.UTF8.GetString(Convert.FromBase64String(base64));
        csv.Split("\r\n", StringSplitOptions.None).Should().HaveCount(103);
        csv.Should().Contain("LIEN-BATCH-100");
    }

    [Fact]
    public void Export_csv_writer_enforces_size_limit_and_formula_safety()
    {
        AutoGeneratedReportService.EscapeCsvField(" \t=SUM(A1:A2)")
            .Should().Be("' \t=SUM(A1:A2)");

        using var stream = new MemoryStream();
        stream.SetLength(AutoGeneratedReportService.ExportByteLimit);
        AutoGeneratedReportService.TryAppendCsvLine(stream, ["value"]).Should().BeFalse();
    }

    [Fact]
    public async Task Execute_returns_not_found_for_cross_tenant_report()
    {
        var report = await AddReportAsync(SeedHelper.TenantId, new DateOnly(2026, 8, 17));
        var otherTenantId = Guid.Parse("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa");
        _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(
            "Bearer",
            JwtTokenHelper.CreateFullAccessToken(otherTenantId, SeedHelper.UserId));

        var response = await _client.PostAsync(
            $"/report/auto-generated/{report.Id}/execute",
            content: null);

        response.StatusCode.Should().Be(HttpStatusCode.NotFound);
    }

    [Fact]
    public async Task Execute_rejects_unregistered_api_path()
    {
        var report = await AddReportAsync(
            SeedHelper.TenantId,
            new DateOnly(2026, 8, 17),
            "/not/allowed");

        var response = await _client.PostAsync(
            $"/report/auto-generated/{report.Id}/execute",
            content: null);

        response.StatusCode.Should().Be(HttpStatusCode.Conflict);
    }

    [Theory]
    [InlineData("/api/liens/reports/weekly-bcc", true)]
    [InlineData("/report/weekly-bcc", true)]
    [InlineData("/report/weekly-bcc/", false)]
    [InlineData("https://example.test/report/weekly-bcc", false)]
    public void Dispatcher_supports_only_exact_registered_paths(string path, bool expected)
    {
        var dispatcher = new AutoGeneratedReportDispatcher(null!);
        dispatcher.Supports(path).Should().Be(expected);
    }

    [Fact]
    public async Task Dispatcher_export_forwards_keyset_batch_parameters()
    {
        var weeklyBcc = new RecordingWeeklyBccReportService();
        var dispatcher = new AutoGeneratedReportDispatcher(weeklyBcc);
        var reportDate = new DateOnly(2026, 8, 17);
        var cursor = new WeeklyBccExportCursor(
            new DateOnly(2026, 8, 1),
            "LIEN-CURSOR",
            Guid.NewGuid());
        using var cancellation = new CancellationTokenSource();
        var report = AutoGeneratedReport.Create(
            SeedHelper.TenantId,
            "weekly_bcc_2026-08-17",
            "Weekly BCC - 08/17/2026",
            reportDate,
            DateTime.UtcNow,
            AutoGeneratedReportDispatcher.CanonicalWeeklyBccPath);

        await dispatcher.ExecuteExportBatchAsync(report, cursor, 250, cancellation.Token);

        weeklyBcc.ExportBatchCalls.Should().Be(1);
        weeklyBcc.TenantId.Should().Be(SeedHelper.TenantId);
        weeklyBcc.AsOfDate.Should().Be(reportDate);
        weeklyBcc.Cursor.Should().Be(cursor);
        weeklyBcc.BatchSize.Should().Be(250);
        weeklyBcc.CancellationToken.Should().Be(cancellation.Token);
    }

    [Fact]
    public async Task Weekly_bcc_export_batches_follow_report_order_without_offset()
    {
        await AddWeeklyBccLiensAsync(
            ("LIEN-C", new DateOnly(2026, 8, 2)),
            ("LIEN-B", new DateOnly(2026, 8, 1)),
            ("LIEN-A", new DateOnly(2026, 8, 1)));

        using var scope = _factory.Services.CreateScope();
        var weeklyBcc = scope.ServiceProvider.GetRequiredService<IWeeklyBccReportService>();
        var first = await weeklyBcc.GetExportBatchAsync(
            SeedHelper.TenantId,
            new DateOnly(2026, 8, 17),
            cursor: null,
            batchSize: 2);
        var second = await weeklyBcc.GetExportBatchAsync(
            SeedHelper.TenantId,
            new DateOnly(2026, 8, 17),
            first.NextCursor,
            batchSize: 2);

        first.Items.Select(row => row.LienId).Should().Equal("LIEN-A", "LIEN-B");
        first.NextCursor.Should().NotBeNull();
        second.Items.Select(row => row.LienId).Should().Equal("LIEN-C");
        second.NextCursor.Should().BeNull();
    }

    [Fact]
    public void Weekly_bcc_export_cursor_query_translates_for_mysql_without_offset()
    {
        var options = new DbContextOptionsBuilder<LiensDbContext>()
            .UseMySql(
                "Server=localhost;Database=translation_only;User=test;Password=test",
                new MySqlServerVersion(new Version(8, 0, 0)))
            .Options;
        using var db = new LiensDbContext(options);
        var service = new WeeklyBccReportService(db);
        var cursor = new WeeklyBccExportCursor(
            new DateOnly(2026, 8, 1),
            "LIEN-CURSOR",
            Guid.Parse("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"));

        var sql = service.BuildExportLienQuery(
                SeedHelper.TenantId,
                new DateOnly(2026, 8, 17),
                cursor,
                batchSize: 500)
            .ToQueryString();

        sql.Should().Contain("ORDER BY");
        sql.Should().Contain("LIMIT");
        sql.Should().NotContain("OFFSET");
    }

    [Fact]
    public async Task Export_stops_fetching_batches_when_csv_size_limit_is_exceeded()
    {
        var report = AutoGeneratedReport.Create(
            SeedHelper.TenantId,
            "weekly_bcc_2026-08-17",
            "Weekly BCC - 08/17/2026",
            new DateOnly(2026, 8, 17),
            DateTime.UtcNow,
            AutoGeneratedReportDispatcher.CanonicalWeeklyBccPath);
        var dispatcher = new OversizedExportDispatcher();
        var service = new AutoGeneratedReportService(
            new SingleReportRepository(report),
            null!,
            dispatcher,
            TimeProvider.System,
            NullLogger<AutoGeneratedReportService>.Instance);

        var result = await service.ExportAsync(SeedHelper.TenantId, reportId: 1);

        result.SizeLimitExceeded.Should().BeTrue();
        dispatcher.BatchCalls.Should().Be(1);
    }

    [Fact]
    public void Scheduler_uses_friday_four_am_across_pst_and_pdt()
    {
        var pacific = WeeklyAutoGeneratedReportHostedService.ResolvePacificTimeZone();

        WeeklyAutoGeneratedReportHostedService.GetLatestDueReportDate(
                new DateTimeOffset(2026, 1, 9, 11, 59, 59, TimeSpan.Zero),
                pacific)
            .Should().Be(new DateOnly(2026, 1, 2));
        WeeklyAutoGeneratedReportHostedService.GetLatestDueReportDate(
                new DateTimeOffset(2026, 1, 9, 12, 0, 0, TimeSpan.Zero),
                pacific)
            .Should().Be(new DateOnly(2026, 1, 9));
        WeeklyAutoGeneratedReportHostedService.GetLatestDueReportDate(
                new DateTimeOffset(2026, 8, 21, 11, 0, 0, TimeSpan.Zero),
                pacific)
            .Should().Be(new DateOnly(2026, 8, 21));
    }

    [Fact]
    public void Scheduler_calculates_exact_next_occurrence()
    {
        var pacific = WeeklyAutoGeneratedReportHostedService.ResolvePacificTimeZone();
        var beforeSummerDue = new DateTimeOffset(2026, 8, 21, 10, 59, 0, TimeSpan.Zero);

        WeeklyAutoGeneratedReportHostedService.GetNextOccurrence(beforeSummerDue, pacific)
            .Should().Be(new DateTimeOffset(2026, 8, 21, 11, 0, 0, TimeSpan.Zero));
    }

    private async Task<AutoGeneratedReport> AddReportAsync(
        Guid tenantId,
        DateOnly reportDate,
        string apiPath = AutoGeneratedReportDispatcher.CanonicalWeeklyBccPath)
    {
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<LiensDbContext>();
        var report = AutoGeneratedReport.Create(
            tenantId,
            $"weekly_bcc_{reportDate:yyyy-MM-dd}",
            $"Weekly BCC - {reportDate:MM/dd/yyyy}",
            reportDate,
            DateTime.UtcNow,
            apiPath);
        db.AutoGeneratedReports.Add(report);
        await db.SaveChangesAsync();
        return report;
    }

    private async Task AddWeeklyBccLiensAsync(params (string LienNumber, DateOnly PurchaseDate)[] rows)
    {
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<LiensDbContext>();
        var caseEntity = Case.Create(
            SeedHelper.TenantId,
            SeedHelper.OrgId,
            $"CASE-PAGE-{Guid.NewGuid():N}",
            "Page",
            "Test",
            SeedHelper.UserId);
        db.Cases.Add(caseEntity);

        foreach (var row in rows)
        {
            db.Liens.Add(Lien.Create(
                SeedHelper.TenantId,
                SeedHelper.OrgId,
                row.LienNumber,
                LienType.MedicalLien,
                100m,
                SeedHelper.UserId,
                caseId: caseEntity.Id,
                purchaseDate: row.PurchaseDate));
        }

        await db.SaveChangesAsync();
    }

    private sealed class RecordingWeeklyBccReportService : IWeeklyBccReportService
    {
        public int ExportBatchCalls { get; private set; }
        public Guid TenantId { get; private set; }
        public DateOnly AsOfDate { get; private set; }
        public WeeklyBccExportCursor? Cursor { get; private set; }
        public int BatchSize { get; private set; }
        public CancellationToken CancellationToken { get; private set; }

        public Task<WeeklyBccReportResult> GetAsync(
            Guid tenantId,
            DateOnly asOfDate,
            CancellationToken ct = default)
        {
            TenantId = tenantId;
            AsOfDate = asOfDate;
            return Task.FromResult(new WeeklyBccReportResult());
        }

        public Task<WeeklyBccReportResult> GetPageAsync(
            Guid tenantId,
            DateOnly asOfDate,
            int page,
            int pageSize,
            bool includeTotalCount = true,
            CancellationToken ct = default)
        {
            return Task.FromResult(new WeeklyBccReportResult());
        }

        public Task<WeeklyBccExportBatch> GetExportBatchAsync(
            Guid tenantId,
            DateOnly asOfDate,
            WeeklyBccExportCursor? cursor,
            int batchSize,
            CancellationToken ct = default)
        {
            ExportBatchCalls++;
            TenantId = tenantId;
            AsOfDate = asOfDate;
            Cursor = cursor;
            BatchSize = batchSize;
            CancellationToken = ct;
            return Task.FromResult(new WeeklyBccExportBatch([], null));
        }
    }

    private sealed class SingleReportRepository(AutoGeneratedReport report) : IAutoGeneratedReportRepository
    {
        public Task<(List<AutoGeneratedReport> Items, int TotalCount)> ListAsync(
            Guid tenantId,
            int page,
            int pageSize,
            CancellationToken ct = default) =>
            throw new NotSupportedException();

        public Task<AutoGeneratedReport?> GetByIdAsync(
            Guid tenantId,
            long reportId,
            CancellationToken ct = default) =>
            Task.FromResult<AutoGeneratedReport?>(
                tenantId == report.TenantId ? report : null);

        public Task<bool> EnsureExistsAsync(
            AutoGeneratedReport value,
            CancellationToken ct = default) =>
            throw new NotSupportedException();
    }

    private sealed class OversizedExportDispatcher : IAutoGeneratedReportDispatcher
    {
        private static readonly AutoGeneratedReportDefinitionResponse Definition = new(
            "WEEKLY_BCC",
            1,
            [new AutoGeneratedReportColumnResponse("plaintiffFirstName", "Plaintiff First Name", 0)]);

        public int BatchCalls { get; private set; }

        public bool Supports(string apiPath) => true;

        public AutoGeneratedReportDefinitionResponse? ResolveDefinition(string apiPath) => Definition;

        public Task<WeeklyBccReportResult> ExecuteAsync(
            AutoGeneratedReport report,
            int page,
            int pageSize,
            bool includeTotalCount = true,
            CancellationToken ct = default) =>
            throw new NotSupportedException();

        public Task<WeeklyBccExportBatch> ExecuteExportBatchAsync(
            AutoGeneratedReport report,
            WeeklyBccExportCursor? cursor,
            int batchSize,
            CancellationToken ct = default)
        {
            BatchCalls++;
            return Task.FromResult(new WeeklyBccExportBatch(
                [new WeeklyBccReportRow
                {
                    PlaintiffFirstName = new string('x', AutoGeneratedReportService.ExportByteLimit),
                }],
                new WeeklyBccExportCursor(
                    report.ReportDate,
                    "LIEN-NEXT",
                    Guid.NewGuid())));
        }
    }
}
