using Liens.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Liens.Infrastructure.Persistence.Configurations;

public sealed class AutoGeneratedReportConfiguration : IEntityTypeConfiguration<AutoGeneratedReport>
{
    public void Configure(EntityTypeBuilder<AutoGeneratedReport> builder)
    {
        builder.ToTable("liens_AutoGeneratedReports");
        builder.HasKey(report => report.Id);

        builder.Property(report => report.Id)
            .ValueGeneratedOnAdd();
        builder.Property(report => report.TenantId)
            .IsRequired();
        builder.Property(report => report.Code)
            .HasMaxLength(100)
            .IsRequired();
        builder.Property(report => report.Description)
            .HasMaxLength(255)
            .IsRequired();
        builder.Property(report => report.ReportDate)
            .HasColumnType("date")
            .IsRequired();
        builder.Property(report => report.CreatedAtUtc)
            .HasColumnType("datetime(6)")
            .IsRequired();
        builder.Property(report => report.ApiPath)
            .HasMaxLength(255)
            .IsRequired();

        builder.HasIndex(report => new { report.TenantId, report.Code })
            .IsUnique()
            .HasDatabaseName("UX_AutoGeneratedReports_TenantId_Code");
        builder.HasIndex(report => new { report.TenantId, report.ApiPath, report.ReportDate })
            .IsUnique()
            .HasDatabaseName("UX_AutoGeneratedReports_TenantId_ApiPath_ReportDate");
        builder.HasIndex(report => new { report.TenantId, report.ReportDate, report.Id })
            .IsDescending(false, true, true)
            .HasDatabaseName("IX_AutoGeneratedReports_TenantId_ReportDate_Id");
    }
}
