// <auto-generated />
using System;
using Commerce.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Commerce.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CommerceDbContext))]
    [Migration("20260424022726_PaymentProviderIntegration")]
    partial class PaymentProviderIntegration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Commerce.Domain.Billing.BillingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LegalName")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_billing_accounts_account_number");

                    b.ToTable("billing_accounts", (string)null);
                });

            modelBuilder.Entity("Commerce.Domain.Billing.BillingAccountAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActorId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("ActorType")
                        .HasColumnType("int");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BillingAccountId", "CreatedAtUtc")
                        .HasDatabaseName("ix_billing_audit_events_account_created");

                    b.ToTable("billing_account_audit_events", (string)null);
                });

            modelBuilder.Entity("Commerce.Domain.Billing.BillingAccountExternalRef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalCustomerRef")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ExternalTenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("HostPlatformKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BillingAccountId")
                        .HasDatabaseName("ix_billing_external_refs_account_id");

                    b.HasIndex("HostPlatformKey", "ExternalTenantId")
                        .IsUnique()
                        .HasDatabaseName("ux_billing_external_refs_host_tenant");

                    b.ToTable("billing_account_external_refs", (string)null);
                });

            modelBuilder.Entity("Commerce.Domain.Billing.BillingContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ContactType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BillingAccountId")
                        .HasDatabaseName("ix_billing_contacts_account_id");

                    b.HasIndex("BillingAccountId", "ContactType")
                        .HasDatabaseName("ix_billing_contacts_account_type");

                    b.ToTable("billing_account_contacts", (string)null);
                });

            modelBuilder.Entity("Commerce.Domain.Billing.BillingProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("char(36)");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("StateRegion")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<bool>("TaxExempt")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BillingAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_billing_profiles_account_id");

                    b.ToTable("billing_account_profiles", (string)null);
                });

            modelBuilder.Entity("Commerce.Domain.Catalog.Addon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_addons_key");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_catalog_addons_product_id");

                    b.ToTable("catalog_addons", (string)null);
                });

            modelBuilder.Entity("Commerce.Domain.Catalog.Bundle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_bundles_key");

                    b.ToTable("catalog_bundles", (string)null);
                });

            modelBuilder.Entity("Commerce.Domain.Catalog.BundleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AddonId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BundleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AddonId");

                    b.HasIndex("BundleId")
                        .HasDatabaseName("ix_catalog_bundle_items_bundle_id");

                    b.HasIndex("PlanId");

                    b.HasIndex("ProductId");

                    b.ToTable("catalog_bundle_items", (string)null);
                });

            modelBuilder.Entity("Commerce.Domain.Catalog.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("FeatureType")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_catalog_features_product_id");

                    b.HasIndex("ProductId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_features_product_key");

                    b.ToTable("catalog_features", (string)null);
                });

            modelBuilder.Entity("Commerce.Domain.Catalog.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("BillingInterval")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TrialDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_plans_key");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_catalog_plans_product_id");

                    b.ToTable("catalog_plans", (string)null);
                });

            modelBuilder.Entity("Commerce.Domain.Catalog.PlanFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("LimitValue")
                        .HasColumnType("bigint");

                    b.Property<long?>("MeteredIncludedUnits")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("PlanId", "FeatureId")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_plan_features_plan_feature");

                    b.ToTable("catalog_plan_features", (string)null);
                });

            modelBuilder.Entity("Commerce.Domain.Catalog.Price", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AddonId")
                        .HasColumnType("char(36)");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint");

                    b.Property<int>("BillingInterval")
                        .HasColumnType("int");

                    b.Property<Guid?>("BundleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AddonId", "Currency", "BillingInterval", "Status")
                        .HasDatabaseName("ix_catalog_prices_addon_lookup");

                    b.HasIndex("BundleId", "Currency", "BillingInterval", "Status")
                        .HasDatabaseName("ix_catalog_prices_bundle_lookup");

                    b.HasIndex("PlanId", "Currency", "BillingInterval", "Status")
                        .HasDatabaseName("ix_catalog_prices_plan_lookup");

                    b.ToTable("catalog_prices", (string)null);
                });

            modelBuilder.Entity("Commerce.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_products_key");

                    b.ToTable("catalog_products", (string)null);
                });

            modelBuilder.Entity("Commerce.Domain.Infrastructure.CommerceSchemaMarker", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.ToTable("commerce_schema_marker", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            SchemaName = "commerce",
                            SchemaVersion = "1.0.0"
                        });
                });

            modelBuilder.Entity("Commerce.Domain.Payments.PaymentMethodReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Brand")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExpMonth")
                        .HasColumnType("int");

                    b.Property<int?>("ExpYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Last4")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<string>("ProviderCustomerId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderPaymentMethodId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BillingAccountId", "Provider")
                        .HasDatabaseName("ix_payment_method_refs_account_provider");

                    b.HasIndex("Provider", "ProviderPaymentMethodId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_method_refs_provider_pmid");

                    b.ToTable("payment_method_references", (string)null);
                });

            modelBuilder.Entity("Commerce.Domain.Payments.PaymentProviderCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<string>("ProviderCustomerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BillingAccountId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_provider_customers_account_provider");

                    b.HasIndex("Provider", "ProviderCustomerId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_provider_customers_provider_pcid");

                    b.ToTable("payment_provider_customers", (string)null);
                });

            modelBuilder.Entity("Commerce.Domain.Payments.PaymentProviderEventLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProcessingStatus")
                        .HasColumnType("int");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingStatus")
                        .HasDatabaseName("ix_payment_provider_event_logs_status");

                    b.HasIndex("Provider", "CreatedAtUtc")
                        .HasDatabaseName("ix_payment_provider_event_logs_provider_created");

                    b.HasIndex("Provider", "ProviderEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_provider_event_logs_provider_eventid");

                    b.ToTable("payment_provider_event_logs", (string)null);
                });

            modelBuilder.Entity("Commerce.Domain.Payments.PaymentProviderSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<string>("ProviderCheckoutSessionId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderCustomerId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderSubscriptionId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ProviderCheckoutSessionId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_provider_subs_provider_csid");

                    b.HasIndex("Provider", "ProviderSubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_provider_subs_provider_psid");

                    b.HasIndex("SubscriptionId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_provider_subs_sub_provider");

                    b.ToTable("payment_provider_subscriptions", (string)null);
                });

            modelBuilder.Entity("Commerce.Domain.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CurrentPeriodEndUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CurrentPeriodStartUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubscriptionNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("TrialEndUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("TrialStartUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BillingAccountId")
                        .HasDatabaseName("ix_subscriptions_billing_account_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_subscriptions_status");

                    b.HasIndex("SubscriptionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_subscriptions_subscription_number");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("Commerce.Domain.Subscriptions.SubscriptionChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ChangeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EffectiveAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("FromPlanId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("FromPriceId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<int>("ProrationBehavior")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ToPlanId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ToPriceId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId", "CreatedAtUtc")
                        .HasDatabaseName("ix_subscription_changes_subscription_created");

                    b.ToTable("subscription_changes", (string)null);
                });

            modelBuilder.Entity("Commerce.Domain.Subscriptions.SubscriptionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("BillingInterval")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PriceId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("char(36)");

                    b.Property<long>("UnitAmountMinor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("PriceId");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_subscription_items_subscription_id");

                    b.HasIndex("SubscriptionId", "Status")
                        .HasDatabaseName("ix_subscription_items_subscription_status");

                    b.ToTable("subscription_items", (string)null);
                });

            modelBuilder.Entity("Commerce.Domain.Billing.BillingAccountAuditEvent", b =>
                {
                    b.HasOne("Commerce.Domain.Billing.BillingAccount", null)
                        .WithMany()
                        .HasForeignKey("BillingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Commerce.Domain.Billing.BillingAccountExternalRef", b =>
                {
                    b.HasOne("Commerce.Domain.Billing.BillingAccount", null)
                        .WithMany()
                        .HasForeignKey("BillingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Commerce.Domain.Billing.BillingContact", b =>
                {
                    b.HasOne("Commerce.Domain.Billing.BillingAccount", null)
                        .WithMany()
                        .HasForeignKey("BillingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Commerce.Domain.Billing.BillingProfile", b =>
                {
                    b.HasOne("Commerce.Domain.Billing.BillingAccount", null)
                        .WithMany()
                        .HasForeignKey("BillingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Commerce.Domain.Catalog.Addon", b =>
                {
                    b.HasOne("Commerce.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Commerce.Domain.Catalog.BundleItem", b =>
                {
                    b.HasOne("Commerce.Domain.Catalog.Addon", null)
                        .WithMany()
                        .HasForeignKey("AddonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Commerce.Domain.Catalog.Bundle", null)
                        .WithMany()
                        .HasForeignKey("BundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Commerce.Domain.Catalog.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Commerce.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Commerce.Domain.Catalog.Feature", b =>
                {
                    b.HasOne("Commerce.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Commerce.Domain.Catalog.Plan", b =>
                {
                    b.HasOne("Commerce.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Commerce.Domain.Catalog.PlanFeature", b =>
                {
                    b.HasOne("Commerce.Domain.Catalog.Feature", null)
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Commerce.Domain.Catalog.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Commerce.Domain.Catalog.Price", b =>
                {
                    b.HasOne("Commerce.Domain.Catalog.Addon", null)
                        .WithMany()
                        .HasForeignKey("AddonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Commerce.Domain.Catalog.Bundle", null)
                        .WithMany()
                        .HasForeignKey("BundleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Commerce.Domain.Catalog.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Commerce.Domain.Payments.PaymentMethodReference", b =>
                {
                    b.HasOne("Commerce.Domain.Billing.BillingAccount", null)
                        .WithMany()
                        .HasForeignKey("BillingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Commerce.Domain.Payments.PaymentProviderCustomer", b =>
                {
                    b.HasOne("Commerce.Domain.Billing.BillingAccount", null)
                        .WithMany()
                        .HasForeignKey("BillingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Commerce.Domain.Payments.PaymentProviderSubscription", b =>
                {
                    b.HasOne("Commerce.Domain.Subscriptions.Subscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Commerce.Domain.Subscriptions.Subscription", b =>
                {
                    b.HasOne("Commerce.Domain.Billing.BillingAccount", null)
                        .WithMany()
                        .HasForeignKey("BillingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Commerce.Domain.Subscriptions.SubscriptionChange", b =>
                {
                    b.HasOne("Commerce.Domain.Subscriptions.Subscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Commerce.Domain.Subscriptions.SubscriptionItem", b =>
                {
                    b.HasOne("Commerce.Domain.Catalog.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Commerce.Domain.Catalog.Price", null)
                        .WithMany()
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Commerce.Domain.Subscriptions.Subscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
