import { CaseListItem } from "../cases";
import { dateConverter } from "../cases/cases.mapper";
import { ExportResponse } from "../cases/cases.types";
import { PaginatedResult } from "../reports/reports.types";
import {
  ApiResponse,
  AutoGeneratedReportItem,
  CaseHistoryItem,
  CaseHistoryParams,
  ColumnGroup,
  CreateReports,
  ExportReportRequest,
  FilterQuery,
  ReportColumnReponse,
  ReportListResponse,
  ReportsResponse,
  ReportTemplate,
  ReportTotals,
  UpdateReportConfigRequest,
  ViewType,
} from "./lien-report.types";
import { lienReportsApi } from "./lien-reports.api";
import {
  mapReportToListItem,
  mapReportToTemplate,
} from "./lien-reports.mapper";

export const lienReportsService = {
  async getReports(): Promise<ReportListResponse> {
    const { data } = await lienReportsApi.list();
    const payload = (data as unknown as { data?: unknown })?.data ?? data;
    const items = Array.isArray(payload) ? payload : [];
    return {
      ...(data as unknown as Record<string, unknown>),
      items: items.map(mapReportToListItem),
    } as ReportListResponse;
  },

  async getReportsById(id: string): Promise<ReportsResponse> {
    const { data } = await lienReportsApi.getById(id);
    return (data as ReportsResponse) ?? ({} as ReportsResponse);
  },

  async generateTemplate(
    request: ReportTemplate | ReportsResponse,
  ): Promise<ReportListResponse> {
    const { data } = await lienReportsApi.createTemplate(
      request as ReportTemplate,
    );
    if (!data) throw new Error("Failed to create report");
    const payload =
      (data as unknown as { data?: unknown; summaryTotals?: ReportTotals })
        ?.data ?? data;
    const items = Array.isArray(payload) ? payload : [];
    return {
      ...(data as unknown as Record<string, unknown>),
      items: items.map(mapReportToTemplate),
      data: items as CaseListItem[],
      reportConfig: data?.reportConfig,
      summaryTotals: (data as unknown as { summaryTotals?: ReportTotals })
        .summaryTotals,
    };
  },
  async createReports(request: CreateReports): Promise<ApiResponse> {
    const { data } = await lienReportsApi.createReport(request);
    if (!data) throw new Error("Failed to create report");
    return data ?? [];
  },

  async exportReports(request: ExportReportRequest): Promise<ExportResponse> {
    const { data } = await lienReportsApi.export(request);
    if (!data) throw new Error("Failed to export report");
    return data as ExportResponse;
  },

  async updateReports(
    request: UpdateReportConfigRequest,
  ): Promise<ApiResponse[]> {
    const { data } = await lienReportsApi.update(request);
    if (!data) throw new Error("Failed to update report");
    return data ?? [];
  },

  async deleteReports(id: string): Promise<ApiResponse[]> {
    const { data } = await lienReportsApi.delete(id);
    if (!data) throw new Error("Failed to delete report");
    return data ?? [];
  },

  async getColumns(viewBy: ViewType): Promise<ReportColumnReponse> {
    const { data } = await lienReportsApi.getColumns(viewBy);
    return data;
  },

  async getFilterOptions(query: FilterQuery): Promise<ApiResponse[]> {
    const { data } = await lienReportsApi.getFilterOptions(query);
    return data.data;
  },
  async getAllFilterOptions(viewBy: ViewType): Promise<ApiResponse[]> {
    const { data } = await lienReportsApi.getAllFilterOptions(viewBy);
    return data.data;
  },

  async getAutoGeneratedReport(query: {
    page: number;
    pageSize: number;
  }): Promise<PaginatedResult<AutoGeneratedReportItem>> {
    const { data } = await lienReportsApi.getAutoGeneratedReport(query);
    return {
      items: data.data.map((r) => {
        return { ...r, createdAt: dateConverter(r.createDate) };
      }),
      totalCount: data.totalCount,
      page: data.page,
      pageSize: data.pageSize,
    };
  },

  async getCaseNotesHistory(
    request: CaseHistoryParams,
  ): Promise<PaginatedResult<CaseHistoryItem>> {
    const { data } = await lienReportsApi.caseNotesHistory(request);
    return {
      items: data.data,
      totalCount: data.totalCount,
      page: data.page,
      pageSize: data?.limit ?? 10,
      totalPages: Math.ceil(data.totalCount / (data?.limit ?? 10)),
    };
  },

  async getAutoGeneratedReportById(reportId: string, query: any): Promise<any> {
    const { data } = await lienReportsApi.getAutoGeneratedReportById(
      reportId,
      query,
    );
    return data;
  },

  async exportcaseNotesHistory(
    request: CaseHistoryParams,
  ): Promise<ApiResponse[]> {
    const { data } = await lienReportsApi.exportCaseNotesHistory(request);
    return data.data;
  },
  async exportAutoGeneratedReport(id: string): Promise<ApiResponse[]> {
    const { data } = await lienReportsApi.exportAutoGeneratedReport(id, {});
    return data.data;
  },
};
