import { apiClient } from "@/lib/api-client";
import {
  ApiResponse,
  AutoGeneratedReportItem,
  AutoGeneratedReportListResponse,
  CaseHistoryItem,
  CaseHistoryParams,
  CreateReports,
  ExportReportRequest,
  FilterQuery,
  PaginatedResultDto,
  ReportColumnReponse,
  ReportListResponse,
  ReportsResponse,
  ReportTemplate,
  UpdateReportConfigRequest,
  ViewType,
} from "./lien-report.types";
import { PaginatedResult, ReportColumnDto } from "../reports/reports.types";
import { ExportResponse } from "../cases/cases.types";

const BASE_PATH = "/lien/report/diy";

function toQs(params: Record<string, unknown>): string {
  const pairs = Object.entries(params)
    .filter(([, v]) => v !== undefined && v !== null && v !== "")
    .map(
      ([k, v]) => `${encodeURIComponent(k)}=${encodeURIComponent(String(v))}`,
    );
  return pairs.length ? `?${pairs.join("&")}` : "";
}

export const lienReportsApi = {
  list() {
    return apiClient.get<ApiResponse>(`/lien/api/liens/reports/diy/saved`);
  },

  getById(id: string) {
    return apiClient.get<ReportsResponse>(
      `/lien/api/liens/reports/diy/saved/${id}`,
    );
  },
  getColumns(viewType: ViewType) {
    return apiClient.get<ReportColumnReponse>(
      `${BASE_PATH}/columns?reportType=${viewType}`,
    );
  },

  getFilterOptions(query: FilterQuery) {
    return apiClient.post<any>(`${BASE_PATH}/filter-options`, query);
  },

  getAllFilterOptions(viewType: ViewType) {
    return apiClient.get<any>(
      `${BASE_PATH}/all-filters?reportType=${viewType}&limit=20`,
    );
  },

  createTemplate(request: ReportTemplate) {
    return apiClient.post<ReportListResponse>(`${BASE_PATH}`, request);
  },

  createReport(request: CreateReports) {
    return apiClient.post<ApiResponse>(`${BASE_PATH}/save`, request);
  },

  export(request: ExportReportRequest) {
    return apiClient.post<ExportResponse>(`${BASE_PATH}/export`, request);
  },

  update(request: UpdateReportConfigRequest) {
    return apiClient.post<ApiResponse[]>(`${BASE_PATH}/export`, request);
  },

  delete(id: string) {
    return apiClient.delete<ApiResponse[]>(
      `/lien/api/liens/reports/diy/saved/${id}`,
    );
  },

  caseNotesHistory(request: CaseHistoryParams) {
    return apiClient.post<PaginatedResultDto<CaseHistoryItem>>(
      `/lien/api/liens/reports/case-notes-history`,
      request,
    );
  },

  getAutoGeneratedReport(query: { page: number; pageSize: number }) {
    return apiClient.get<
      PaginatedResultDto<AutoGeneratedReportItem> &
        AutoGeneratedReportListResponse
    >(`/lien/api/liens/reports/auto-generated${toQs(query)}`);
  },

  getAutoGeneratedReportById(reportId: string, query: any) {
    return apiClient.post<PaginatedResultDto<AutoGeneratedReportItem>>(
      `/lien/api/liens/reports/auto-generated/${reportId}/execute${toQs(query)}`,
      query,
    );
  },

  exportCaseNotesHistory(request: CaseHistoryParams) {
    return apiClient.post<any>(
      `/lien/api/liens/reports/case-notes-history/export`,
      request,
    );
  },
  exportAutoGeneratedReport(reportId: string, query: any) {
    return apiClient.post<any>(
      `/lien/api/liens/reports/auto-generated/${reportId}/export${toQs(query)}`,
      query,
    );
  },
};
