using Liens.Application.DTOs;
using Liens.Domain.Entities;

namespace Liens.Application.Interfaces;

public interface IAutoGeneratedReportService
{
    Task<AutoGeneratedReportPage> ListAsync(
        Guid tenantId,
        int page,
        int pageSize,
        CancellationToken ct = default);

    Task<AutoGeneratedReportExecutionResult> ExecuteAsync(
        Guid tenantId,
        long reportId,
        CancellationToken ct = default);

    Task<AutoGeneratedReportReconciliationResult> ReconcileWeeklyBccAsync(
        DateOnly reportDate,
        CancellationToken ct = default);
}

public interface IAutoGeneratedReportTenantSource
{
    Task<IReadOnlyList<Guid>> ListEligibleTenantIdsAsync(CancellationToken ct = default);
}

public interface IAutoGeneratedReportDispatcher
{
    bool Supports(string apiPath);

    Task<WeeklyBccReportResult> ExecuteAsync(
        AutoGeneratedReport report,
        CancellationToken ct = default);
}
