// <auto-generated />
//
// TB-DATA-02 — minimal Designer placeholder. Authoritative DDL lives in
// the sibling 20260516120000_TenantBillingEntitlementSnapshots.cs file.
// See the WRITE-005 / ERP-001 / ERP-003 / TB-DATA-01 reports for the
// same convention: the maintainer must regenerate this Designer's
// BuildTargetModel body AND the project-level
// BillingDbContextModelSnapshot.cs in a dotnet-SDK-equipped
// environment before adding the next schema-touching migration.
//
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Billing.Infrastructure.Data;

#nullable disable

namespace Billing.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260516120000_TenantBillingEntitlementSnapshots")]
    partial class TenantBillingEntitlementSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Intentionally empty — see file header.
#pragma warning restore 612, 618
        }
    }
}
