// <auto-generated />
//
// MS-BILL-INT-001 — minimal Designer placeholder.
//
// The authoritative DDL for this migration lives in the sibling
// <c>20260513140000_AddStatementDeliveryFields.cs</c> file and is
// applied at runtime by <c>EF Core MigrationBuilder</c>. This
// Designer file is required for the migration to load (the
// <c>[Migration]</c> attribute pairs an Up/Down with a target
// model snapshot), but in this Replit environment the .NET SDK
// is unavailable so the full snapshot cannot be regenerated by
// <c>dotnet ef migrations add</c>. The maintainer must regenerate
// both this Designer's <c>BuildTargetModel</c> body AND the
// project-level <c>BillingDbContextModelSnapshot.cs</c> in a
// dotnet-SDK-equipped environment before adding the next
// schema-touching migration. See the INT-001 report's "Known
// gaps" section.
//
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Billing.Infrastructure.Data;

#nullable disable

namespace Billing.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260513140000_AddStatementDeliveryFields")]
    partial class AddStatementDeliveryFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally empty — see file header.
        }
    }
}
