// <auto-generated />
//
// MS-BILL-ERP-006 — minimal Designer placeholder.
//
// The authoritative DDL for this migration lives in the sibling
// 20260514150000_AddBulkMappingImportHistory.cs file and is applied
// at runtime by EF Core MigrationBuilder. This Designer file is
// required for the migration to load (the [Migration] attribute
// pairs an Up/Down with a target model snapshot), but in this Replit
// environment the .NET SDK is unavailable so the full snapshot
// cannot be regenerated by `dotnet ef migrations add`.
//
// The maintainer must regenerate both this Designer's
// BuildTargetModel body AND the project-level
// BillingDbContextModelSnapshot.cs in a dotnet-SDK-equipped
// environment before adding the next schema-touching migration.
// See the WRITE-005 / INT-001 / ERP-001 / ERP-003 reports for the
// same convention.
//
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Billing.Infrastructure.Data;

#nullable disable

namespace Billing.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260514150000_AddBulkMappingImportHistory")]
    partial class AddBulkMappingImportHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Intentionally empty — see file header.
#pragma warning restore 612, 618
        }
    }
}
