using Liens.Application.Repositories;
using Liens.Domain.Entities;
using Liens.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using MySqlConnector;

namespace Liens.Infrastructure.Repositories;

public sealed class AutoGeneratedReportRepository : IAutoGeneratedReportRepository
{
    private readonly DbContextOptions<LiensDbContext> _dbOptions;

    public AutoGeneratedReportRepository(DbContextOptions<LiensDbContext> dbOptions)
    {
        _dbOptions = dbOptions;
    }

    public async Task<(List<AutoGeneratedReport> Items, int TotalCount)> ListAsync(
        Guid tenantId,
        int page,
        int pageSize,
        CancellationToken ct = default)
    {
        await using var db = new LiensDbContext(_dbOptions);
        var query = db.AutoGeneratedReports
            .AsNoTracking()
            .Where(report => report.TenantId == tenantId);

        var totalCount = await query.CountAsync(ct);
        var items = await query
            .OrderByDescending(report => report.ReportDate)
            .ThenByDescending(report => report.Id)
            .Skip((page - 1) * pageSize)
            .Take(pageSize)
            .ToListAsync(ct);

        return (items, totalCount);
    }

    public async Task<AutoGeneratedReport?> GetByIdAsync(
        Guid tenantId,
        long reportId,
        CancellationToken ct = default)
    {
        await using var db = new LiensDbContext(_dbOptions);
        return await db.AutoGeneratedReports
            .AsNoTracking()
            .FirstOrDefaultAsync(
                report => report.TenantId == tenantId && report.Id == reportId,
                ct);
    }

    public async Task<bool> EnsureExistsAsync(
        AutoGeneratedReport report,
        CancellationToken ct = default)
    {
        await using var db = new LiensDbContext(_dbOptions);
        db.AutoGeneratedReports.Add(report);

        try
        {
            await db.SaveChangesAsync(ct);
            return true;
        }
        catch (DbUpdateException ex) when (IsDuplicateKey(ex))
        {
            return false;
        }
    }

    private static bool IsDuplicateKey(Exception exception)
    {
        for (var current = exception; current is not null; current = current.InnerException)
        {
            if (current is MySqlException { Number: 1062 })
                return true;
        }

        return false;
    }
}
