namespace Liens.Application.DTOs;

public sealed record AutoGeneratedReportResponse(
    long ReportId,
    string Code,
    string Description,
    DateOnly Date,
    DateTime CreateDate,
    Guid TenantId,
    string ApiPath);

public sealed record AutoGeneratedReportPage(
    IReadOnlyList<AutoGeneratedReportResponse> Items,
    int Page,
    int PageSize,
    int TotalCount);

public enum AutoGeneratedReportExecutionStatus
{
    Success,
    NotFound,
    UnsupportedPath,
}

public sealed record AutoGeneratedReportExecutionResult(
    AutoGeneratedReportExecutionStatus Status,
    AutoGeneratedReportResponse? Report = null,
    WeeklyBccReportResult? WeeklyBcc = null);

public sealed record AutoGeneratedReportReconciliationResult(
    DateOnly ReportDate,
    int EligibleTenantCount,
    int InsertedCount,
    int ExistingCount,
    int FailedCount);
