namespace Liens.Application.DTOs;

public sealed record AutoGeneratedReportResponse(
    long ReportId,
    string Code,
    string Description,
    DateOnly Date,
    DateTime CreateDate,
    Guid TenantId,
    string ApiPath);

public sealed record AutoGeneratedReportPage(
    IReadOnlyList<AutoGeneratedReportResponse> Items,
    int Page,
    int PageSize,
    int TotalCount);

public enum AutoGeneratedReportExecutionStatus
{
    Success,
    NotFound,
    UnsupportedPath,
}

public sealed record AutoGeneratedReportColumnResponse(
    string Key,
    string Label,
    int Index);

public sealed record AutoGeneratedReportDefinitionResponse(
    string ReportType,
    int SchemaVersion,
    IReadOnlyList<AutoGeneratedReportColumnResponse> Columns);

public sealed record AutoGeneratedReportExecutionResult(
    AutoGeneratedReportExecutionStatus Status,
    AutoGeneratedReportResponse? Report = null,
    WeeklyBccReportResult? WeeklyBcc = null,
    AutoGeneratedReportDefinitionResponse? Definition = null);

public sealed record AutoGeneratedReportExportResult(
    AutoGeneratedReportExecutionStatus Status,
    AutoGeneratedReportResponse? Report = null,
    Stream? Content = null,
    bool SizeLimitExceeded = false) : IAsyncDisposable
{
    public ValueTask DisposeAsync() =>
        Content?.DisposeAsync() ?? ValueTask.CompletedTask;
}

public sealed record AutoGeneratedReportReconciliationResult(
    DateOnly ReportDate,
    int EligibleTenantCount,
    int InsertedCount,
    int ExistingCount,
    int FailedCount);
