using Microsoft.EntityFrameworkCore.Migrations;

namespace Liens.Infrastructure.Persistence.Migrations;

internal static class AutoGeneratedReportSchemaMigrationGuards
{
    public static void CreateTableIfMissing(MigrationBuilder migrationBuilder, string sql)
        => migrationBuilder.Sql(Terminate(sql), suppressTransaction: true);

    public static void CreateIndexIfMissing(
        MigrationBuilder migrationBuilder,
        string table,
        string index,
        string columns,
        bool unique = false)
    {
        var ddl = $"CREATE {(unique ? "UNIQUE " : string.Empty)}INDEX `{index}` ON `{table}` {columns}";
        var escapedDdl = ddl.Replace("'", "''", StringComparison.Ordinal);

        migrationBuilder.Sql(
            $"""
            SET @legalsynq_auto_report_ddl = IF(
                (SELECT COUNT(*)
                 FROM information_schema.STATISTICS
                 WHERE TABLE_SCHEMA = DATABASE()
                   AND TABLE_NAME = '{table}'
                   AND INDEX_NAME = '{index}') = 0,
                '{escapedDdl}',
                'SELECT 1');
            PREPARE legalsynq_auto_report_stmt FROM @legalsynq_auto_report_ddl;
            EXECUTE legalsynq_auto_report_stmt;
            DEALLOCATE PREPARE legalsynq_auto_report_stmt;
            """,
            suppressTransaction: true);
    }

    private static string Terminate(string sql)
    {
        var normalized = sql.TrimEnd();
        return normalized.EndsWith(';') ? normalized : $"{normalized};";
    }
}
