// <auto-generated />
using System;
using Liens.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Liens.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LiensDbContext))]
    partial class LiensDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Liens.Domain.Entities.BatchTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ColumnsHeader")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_BatchTemplates_TenantId_Code");

                    b.ToTable("liens_BatchTemplates", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.BatchUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BatchDate")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("DataContext")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ProcessStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Rows")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Status", "CreatedAtUtc")
                        .HasDatabaseName("IX_BatchUploads_TenantId_Status_CreatedAt");

                    b.ToTable("liens_BatchUploads", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.BatchUploadDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BatchUploadId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("BatchUploadId", "RecordStatus", "RowNumber")
                        .HasDatabaseName("IX_BatchUploadDetails_BatchUploadId_RecordStatus_RowNumber");

                    b.ToTable("liens_BatchUploadDetails", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.BillOfSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BillOfSaleNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BuyerContactName")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("BuyerOrgId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("EffectiveAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExecutedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LienId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("LienOfferId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<decimal>("OriginalLienAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PurchaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SellerContactName")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("SellerOrgId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Terms")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("IX_BillsOfSale_DocumentId");

                    b.HasIndex("LienId")
                        .HasDatabaseName("IX_BillsOfSale_LienId");

                    b.HasIndex("LienOfferId")
                        .HasDatabaseName("IX_BillsOfSale_LienOfferId");

                    b.HasIndex("TenantId", "BillOfSaleNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_BillsOfSale_TenantId_BillOfSaleNumber");

                    b.HasIndex("TenantId", "BuyerOrgId")
                        .HasDatabaseName("IX_BillsOfSale_TenantId_BuyerOrgId");

                    b.HasIndex("TenantId", "SellerOrgId")
                        .HasDatabaseName("IX_BillsOfSale_TenantId_SellerOrgId");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_BillsOfSale_TenantId_Status");

                    b.ToTable("liens_BillsOfSale", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ClaimNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClientAddress")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateOnly?>("ClientDob")
                        .HasColumnType("date");

                    b.Property<string>("ClientEmail")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("ClientFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClientLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClientPhone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("DateOfIncident")
                        .HasColumnType("date");

                    b.Property<decimal?>("DemandAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("InsuranceCarrier")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("OpenedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PolicyNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("SettlementAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CaseNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Cases_TenantId_CaseNumber");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_Cases_TenantId_Status");

                    b.HasIndex("TenantId", "OrgId", "CreatedAtUtc")
                        .HasDatabaseName("IX_Cases_TenantId_OrgId_CreatedAtUtc");

                    b.HasIndex("TenantId", "OrgId", "Status")
                        .HasDatabaseName("IX_Cases_TenantId_OrgId_Status");

                    b.ToTable("liens_Cases", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContactSubtype")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<Guid?>("FacilityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Fax")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("LawFirmId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Organization")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .HasDatabaseName("IX_Contacts_TenantId_Email");

                    b.HasIndex("TenantId", "FacilityId", "ContactSubtype")
                        .HasDatabaseName("IX_Contacts_TenantId_FacilityId_ContactSubtype");

                    b.HasIndex("TenantId", "LawFirmId", "ContactSubtype")
                        .HasDatabaseName("IX_Contacts_TenantId_LawFirmId_ContactSubtype");

                    b.HasIndex("TenantId", "OrgId", "ContactType")
                        .HasDatabaseName("IX_Contacts_TenantId_OrgId_ContactType");

                    b.HasIndex("TenantId", "OrgId", "DisplayName")
                        .HasDatabaseName("IX_Contacts_TenantId_OrgId_DisplayName");

                    b.ToTable("liens_Contacts", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.DIYReportConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId");

                    b.ToTable("liens_DIYReportConfigs", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Fax")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_Facilities_OrganizationId");

                    b.HasIndex("TenantId", "Code")
                        .HasDatabaseName("IX_Facilities_TenantId_Code");

                    b.HasIndex("TenantId", "OrgId", "Name")
                        .HasDatabaseName("IX_Facilities_TenantId_OrgId_Name");

                    b.ToTable("liens_Facilities", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.FacilityContactPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Position")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("TenantId", "FacilityId");

                    b.ToTable("liens_FacilityContactPersons", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.Lien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ArchivedReason")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal?>("AskAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("BuyingOrgId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateOnly?>("EndServiceDate")
                        .HasColumnType("date");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("FacilityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("FundingCompanyContactId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("FundingCompanyId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("HighestBidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("HoldingOrgId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("IncidentDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("InitialServiceDate")
                        .HasColumnType("date");

                    b.Property<string>("IsBulk")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsConfidential")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IsServicing")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Jurisdiction")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LienNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LienType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ListingVisibility")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<decimal?>("OfferPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("OpenedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("OriginalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PayoffAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SellerStatus")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("SellingOrgId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("SoldAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SubjectFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SubjectLastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("SubjectPartyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("SubmittedForSaleAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("WithdrawnAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("IX_Liens_CaseId");

                    b.HasIndex("FacilityId")
                        .HasDatabaseName("IX_Liens_FacilityId");

                    b.HasIndex("TenantId", "BuyingOrgId")
                        .HasDatabaseName("IX_Liens_TenantId_BuyingOrgId");

                    b.HasIndex("TenantId", "CreatedAtUtc")
                        .HasDatabaseName("IX_Liens_TenantId_CreatedAtUtc");

                    b.HasIndex("TenantId", "LienNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Liens_TenantId_LienNumber");

                    b.HasIndex("TenantId", "LienType")
                        .HasDatabaseName("IX_Liens_TenantId_LienType");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_Liens_TenantId_Status");

                    b.HasIndex("TenantId", "HoldingOrgId", "Status")
                        .HasDatabaseName("IX_Liens_TenantId_HoldingOrgId_Status");

                    b.HasIndex("TenantId", "OrgId", "Status")
                        .HasDatabaseName("IX_Liens_TenantId_OrgId_Status");

                    b.HasIndex("TenantId", "SellerStatus", "ListingVisibility")
                        .HasDatabaseName("IX_Liens_Tenant_SellerStatus_Visibility");

                    b.HasIndex("TenantId", "SellingOrgId", "InitialServiceDate")
                        .HasDatabaseName("IX_Liens_Tenant_Seller_InitialService");

                    b.HasIndex("TenantId", "SellingOrgId", "SellerStatus")
                        .HasDatabaseName("IX_Liens_TenantId_SellingOrgId_SellerStatus");

                    b.HasIndex("TenantId", "SellingOrgId", "Status")
                        .HasDatabaseName("IX_Liens_TenantId_SellingOrgId_Status");

                    b.HasIndex("TenantId", "SellingOrgId", "FundingCompanyId", "SellerStatus")
                        .HasDatabaseName("IX_Liens_Tenant_Seller_Funding_Status");

                    b.HasIndex("TenantId", "SellingOrgId", "SellerStatus", "SoldAtUtc")
                        .HasDatabaseName("IX_Liens_Tenant_Seller_Status_Sold");

                    b.HasIndex("TenantId", "SellingOrgId", "SellerStatus", "SubmittedForSaleAtUtc")
                        .HasDatabaseName("IX_Liens_Tenant_Seller_Status_Submitted");

                    b.ToTable("liens_Liens", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.LienCaseNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("general");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId", "IsDeleted")
                        .HasDatabaseName("IX_CaseNotes_CaseId_IsDeleted");

                    b.HasIndex("TenantId", "CaseId", "CreatedAtUtc")
                        .HasDatabaseName("IX_CaseNotes_TenantId_CaseId_CreatedAt");

                    b.ToTable("liens_CaseNotes", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.LienGeneratedTaskMetadata", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("GenerationRuleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("TaskTemplateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TriggerEntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TriggerEntityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TriggerEventType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("TaskId");

                    b.HasIndex("TenantId", "GenerationRuleId")
                        .HasDatabaseName("IX_GeneratedTaskMetadata_TenantId_RuleId");

                    b.ToTable("liens_GeneratedTaskMetadata", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.LienOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BuyerOrgId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("LienId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<decimal>("OfferAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OfferedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResponseNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<Guid>("SellerOrgId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("WithdrawnAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("LienId");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_LienOffers_TenantId_Status");

                    b.HasIndex("TenantId", "BuyerOrgId", "Status")
                        .HasDatabaseName("IX_LienOffers_TenantId_BuyerOrgId_Status");

                    b.HasIndex("TenantId", "LienId", "Status")
                        .HasDatabaseName("IX_LienOffers_TenantId_LienId_Status");

                    b.HasIndex("TenantId", "SellerOrgId", "OfferedAtUtc")
                        .HasDatabaseName("IX_LienOffers_Tenant_Seller_OfferedAt");

                    b.HasIndex("TenantId", "SellerOrgId", "Status")
                        .HasDatabaseName("IX_LienOffers_TenantId_SellerOrgId_Status");

                    b.ToTable("liens_LienOffers", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.LienReduction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("LienId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateOnly>("ReductionDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CaseId");

                    b.HasIndex("TenantId", "LienId");

                    b.ToTable("liens_LienReductions", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.LienSettlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("LienId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("PaymentNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CaseId");

                    b.HasIndex("TenantId", "LienId");

                    b.ToTable("liens_LienSettlements", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.LienTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("GeneratingTemplateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("GenerationRuleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("MANUAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("WorkflowInstanceId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("WorkflowStageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("WorkflowStepKey")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AssignedUserId")
                        .HasDatabaseName("IX_Tasks_TenantId_AssignedUserId");

                    b.HasIndex("TenantId", "CaseId")
                        .HasDatabaseName("IX_Tasks_TenantId_CaseId");

                    b.HasIndex("TenantId", "CreatedAtUtc")
                        .HasDatabaseName("IX_Tasks_TenantId_CreatedAtUtc");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_Tasks_TenantId_Status");

                    b.HasIndex("TenantId", "WorkflowInstanceId")
                        .HasDatabaseName("IX_Tasks_TenantId_WorkflowInstanceId");

                    b.ToTable("liens_Tasks", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.LienTaskGenerationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ApplicableWorkflowStageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AssignmentMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("ContextType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("DueDateMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int?>("DueDateOffsetDays")
                        .HasColumnType("int");

                    b.Property<string>("DuplicatePreventionMode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastUpdatedByName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("LastUpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LastUpdatedSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("TaskTemplateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EventType")
                        .HasDatabaseName("IX_TaskGenerationRules_TenantId_EventType");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("IX_TaskGenerationRules_TenantId_IsActive");

                    b.ToTable("liens_TaskGenerationRules", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.LienTaskLienLink", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("LienId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("TaskId", "LienId");

                    b.HasIndex("LienId")
                        .HasDatabaseName("IX_TaskLienLinks_LienId");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("IX_TaskLienLinks_TaskId");

                    b.ToTable("liens_TaskLienLinks", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.LienTaskNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "IsDeleted")
                        .HasDatabaseName("IX_TaskNotes_TaskId_IsDeleted");

                    b.HasIndex("TenantId", "TaskId", "CreatedAtUtc")
                        .HasDatabaseName("IX_TaskNotes_TenantId_TaskId_CreatedAt");

                    b.ToTable("liens_TaskNotes", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.LienWorkflowConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastUpdatedByName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("LastUpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LastUpdatedSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProductCode")
                        .IsUnique()
                        .HasDatabaseName("UX_WorkflowConfigs_TenantId_ProductCode");

                    b.ToTable("liens_WorkflowConfigs", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.LienWorkflowStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("DefaultOwnerRole")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SlaMetadata")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("StageOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkflowConfigId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowConfigId", "StageOrder")
                        .HasDatabaseName("IX_WorkflowStages_ConfigId_Order");

                    b.ToTable("liens_WorkflowStages", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.LienWorkflowTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FromStageId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("ToStageId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkflowConfigId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("FromStageId");

                    b.HasIndex("ToStageId");

                    b.HasIndex("WorkflowConfigId", "FromStageId")
                        .HasDatabaseName("IX_WorkflowTransitions_WorkflowId_FromStage");

                    b.HasIndex("WorkflowConfigId", "FromStageId", "ToStageId")
                        .IsUnique()
                        .HasDatabaseName("UX_WorkflowTransitions_Unique");

                    b.ToTable("liens_WorkflowTransitions", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.LookupValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Category")
                        .HasDatabaseName("IX_LookupValues_TenantId_Category");

                    b.HasIndex("TenantId", "Category", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_LookupValues_TenantId_Category_Code");

                    b.ToTable("liens_LookupValues", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.ManualMedicalCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Copay")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("FacilityTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FacilityType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("ASC");

                    b.Property<decimal>("PhysicianTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasDefaultValue("A");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .HasDatabaseName("IX_ManualMedicalCodes_TenantId_Code");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_ManualMedicalCodes_TenantId_Status");

                    b.ToTable("liens_ManualMedicalCodes", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.SellingBuyerAccessLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BuyerContactId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BuyerOrgId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("varchar(280)");

                    b.Property<DateTime?>("LastAccessedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LienId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("NotificationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NotificationStatus")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("NotificationSubmittedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SellerOrgId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("LienId");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_SellingBuyerAccessLinks_TenantId_IdempotencyKey");

                    b.HasIndex("TenantId", "Token")
                        .IsUnique()
                        .HasDatabaseName("UX_SellingBuyerAccessLinks_TenantId_Token");

                    b.HasIndex("TenantId", "LienId", "BuyerContactId")
                        .HasDatabaseName("IX_SellingBuyerAccessLinks_Tenant_Lien_BuyerContact");

                    b.ToTable("liens_SellingBuyerAccessLinks", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.SellingPortfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("CurrentBalanceTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("LienCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal?>("OfferPriceTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OriginalAmountTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PortfolioNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SellerOrgId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TargetGrouping")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PortfolioNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_SellingPortfolios_TenantId_PortfolioNumber");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_SellingPortfolios_TenantId_Status");

                    b.HasIndex("TenantId", "SellerOrgId", "Status")
                        .HasDatabaseName("IX_SellingPortfolios_TenantId_SellerOrgId_Status");

                    b.ToTable("liens_SellingPortfolios", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.SellingPortfolioActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("json");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("TenantId", "PortfolioId", "OccurredAtUtc")
                        .HasDatabaseName("IX_SellingPortfolioActivities_TenantId_PortfolioId_OccurredAtUtc");

                    b.ToTable("liens_SellingPortfolioActivities", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.SellingPortfolioBuyer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BuyerOrgId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("TenantId", "BuyerOrgId")
                        .HasDatabaseName("IX_SellingPortfolioBuyers_TenantId_BuyerOrgId");

                    b.HasIndex("TenantId", "PortfolioId", "BuyerOrgId")
                        .IsUnique()
                        .HasDatabaseName("UX_SellingPortfolioBuyers_TenantId_PortfolioId_BuyerOrgId");

                    b.ToTable("liens_SellingPortfolioBuyers", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.SellingPortfolioLien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CaseExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<Guid?>("FacilityId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("IncidentDate")
                        .HasColumnType("date");

                    b.Property<string>("Jurisdiction")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LienExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("LienId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LienLifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LienNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LienType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("OfferPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OriginalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PayoffAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SubjectFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SubjectLastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("LienId");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("TenantId", "CaseId")
                        .HasDatabaseName("IX_SellingPortfolioLiens_TenantId_CaseId");

                    b.HasIndex("TenantId", "LienId")
                        .HasDatabaseName("IX_SellingPortfolioLiens_TenantId_LienId");

                    b.HasIndex("TenantId", "PortfolioId", "LienId")
                        .IsUnique()
                        .HasDatabaseName("UX_SellingPortfolioLiens_TenantId_PortfolioId_LienId");

                    b.ToTable("liens_SellingPortfolioLiens", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.SellingPortfolioStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("TenantId", "PortfolioId", "ChangedAtUtc")
                        .HasDatabaseName("IX_SellingPortfolioStatusHistory_TenantId_PortfolioId_ChangedAtUtc");

                    b.ToTable("liens_SellingPortfolioStatusHistory", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.ServicingItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EscalatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LienId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Resolution")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TaskNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AssignedTo")
                        .HasDatabaseName("IX_ServicingItems_TenantId_AssignedTo");

                    b.HasIndex("TenantId", "CaseId")
                        .HasDatabaseName("IX_ServicingItems_TenantId_CaseId");

                    b.HasIndex("TenantId", "LienId")
                        .HasDatabaseName("IX_ServicingItems_TenantId_LienId");

                    b.HasIndex("TenantId", "Priority")
                        .HasDatabaseName("IX_ServicingItems_TenantId_Priority");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_ServicingItems_TenantId_Status");

                    b.HasIndex("TenantId", "TaskNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_ServicingItems_TenantId_TaskNumber");

                    b.ToTable("liens_ServicingItems", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.SettlementPaymentDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CheckNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("LienId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Payee")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<int>("PaymentNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CaseId");

                    b.HasIndex("TenantId", "LienId");

                    b.ToTable("liens_SettlementPaymentDetails", (string)null);
                });

            modelBuilder.Entity("Liens.Domain.Entities.BatchUploadDetail", b =>
                {
                    b.HasOne("Liens.Domain.Entities.BatchUpload", null)
                        .WithMany("Details")
                        .HasForeignKey("BatchUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Liens.Domain.Entities.BillOfSale", b =>
                {
                    b.HasOne("Liens.Domain.Entities.Lien", null)
                        .WithMany()
                        .HasForeignKey("LienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Liens.Domain.Entities.LienOffer", null)
                        .WithMany()
                        .HasForeignKey("LienOfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Liens.Domain.Entities.FacilityContactPerson", b =>
                {
                    b.HasOne("Liens.Domain.Entities.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("Liens.Domain.Entities.Lien", b =>
                {
                    b.HasOne("Liens.Domain.Entities.Case", null)
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Liens.Domain.Entities.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Liens.Domain.Entities.LienOffer", b =>
                {
                    b.HasOne("Liens.Domain.Entities.Lien", null)
                        .WithMany()
                        .HasForeignKey("LienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Liens.Domain.Entities.LienWorkflowStage", b =>
                {
                    b.HasOne("Liens.Domain.Entities.LienWorkflowConfig", null)
                        .WithMany("Stages")
                        .HasForeignKey("WorkflowConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Liens.Domain.Entities.LienWorkflowTransition", b =>
                {
                    b.HasOne("Liens.Domain.Entities.LienWorkflowStage", null)
                        .WithMany()
                        .HasForeignKey("FromStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Liens.Domain.Entities.LienWorkflowStage", null)
                        .WithMany()
                        .HasForeignKey("ToStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Liens.Domain.Entities.LienWorkflowConfig", null)
                        .WithMany("Transitions")
                        .HasForeignKey("WorkflowConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Liens.Domain.Entities.SellingBuyerAccessLink", b =>
                {
                    b.HasOne("Liens.Domain.Entities.Lien", null)
                        .WithMany()
                        .HasForeignKey("LienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Liens.Domain.Entities.SellingPortfolioActivity", b =>
                {
                    b.HasOne("Liens.Domain.Entities.SellingPortfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Liens.Domain.Entities.SellingPortfolioBuyer", b =>
                {
                    b.HasOne("Liens.Domain.Entities.SellingPortfolio", null)
                        .WithMany("Buyers")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Liens.Domain.Entities.SellingPortfolioLien", b =>
                {
                    b.HasOne("Liens.Domain.Entities.Lien", null)
                        .WithMany()
                        .HasForeignKey("LienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Liens.Domain.Entities.SellingPortfolio", null)
                        .WithMany("Liens")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Liens.Domain.Entities.SellingPortfolioStatusHistory", b =>
                {
                    b.HasOne("Liens.Domain.Entities.SellingPortfolio", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Liens.Domain.Entities.BatchUpload", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Liens.Domain.Entities.LienWorkflowConfig", b =>
                {
                    b.Navigation("Stages");

                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("Liens.Domain.Entities.SellingPortfolio", b =>
                {
                    b.Navigation("Buyers");

                    b.Navigation("Liens");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
