"use client";

import { BaseTable } from "@/components/ui/base-table";
import { PaginationMeta } from "@/lib/contacts";
import {
  ColumnGroup,
  CreateReports,
  ExportReportRequest,
  ReportColumnOption,
  ReportListResponse,
  ReportTotals,
} from "@/lib/liens/lien-report.types";

type SummaryTotals = {
  summaryTotals: ReportTotals;
};
interface ReportDisplayProps {
  report: any;
  columns: any;
  onBack: () => void;
  onPaginate?: (pagination: PaginationMeta) => void;
  loadingData?: boolean;
  exporting?: boolean;

  onExport?: () => void;
}

function formatCurrency(amount: number | null): string {
  if (amount === null || amount === undefined || isNaN(Number(amount)))
    return "";

  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 2, // Forces decimals like .00 if needed
  }).format(Number(amount));
}
function formatNumber(amount: number): string {
  return new Intl.NumberFormat("en-IN", { maximumSignificantDigits: 3 }).format(
    amount,
  );
}

export default function AutoGeneratedReportDisplay({
  report,
  onBack,
  onExport,
  onPaginate,
  loadingData,
  exporting,
  columns,
}: ReportDisplayProps) {
  const pagination: PaginationMeta = {
    page: report.page ?? 1,
    pageSize: report.pageSize ?? 10,
    totalCount: report?.totalCount ?? 0,
    totalPages: report?.totalPages ?? 1,
  };

  return (
    <div className="min-h-screen space-y-6">
      {/* TABLE PLACEHOLDER */}
      <div className="bg-white overflow-x-scroll h-full">
        {loadingData ? (
          <div className="py-12 text-center">
            <div className="inline-block h-5 w-5 animate-spin rounded-full border-2 border-primary border-t-transparent" />
            <p className="text-sm text-gray-400 mt-2">Loading reports...</p>
          </div>
        ) : (
          <>
            <div className="flex justify-between items-center bg-white p-4 rounded-xl border border-gray-200 mb-6">
              <div>
                <h2 className="text-lg font-semibold">{report?.report?.description}</h2>

               <p className="text-sm text-gray-500">
                Auto generated report
               </p>
              </div>
            </div>
            <div className="overflow-x-auto">
              <BaseTable
                data={report.data ?? []}
                columns={columns}
                isLoading={loadingData}
                emptyMessage="No data found."
                manualPagination
                enableSorting={false}
                pageCount={pagination.totalPages}
                totalCount={pagination.totalCount}
                pagination={{
                  pageIndex: pagination.page - 1,
                  pageSize: pagination.pageSize,
                }}
                enableExpanding={true}
                onPaginationChange={(updater) => {
                  const next =
                    typeof updater === "function"
                      ? updater({
                          pageIndex: pagination.page - 1,
                          pageSize: pagination.pageSize,
                        })
                      : updater;
                  onPaginate?.({ ...pagination, page: next.pageIndex + 1 });
                }}
                className="bg-white border-gray-200 !rounded-none"
              />
            </div>
          </>
        )}
      </div>

      <div className="bg-white border border-gray-200 rounded-xl p-6 text-sm text-gray-500">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          {/* LEFT */}
          <button
            onClick={onBack}
            className="px-3 py-2 border border-gray-200 text-[#0A0A0A] font-semibold rounded-lg text-sm self-start hover:shadow-sm"
          >
            Back
          </button>
          {/* RIGHT */}
          <div className="flex flex-wrap gap-2 sm:gap-2 sm:flex-row sm:items-center sm:justify-end">
            <button
              disabled={exporting}
              onClick={onExport}
              className="px-3 py-2 border border-gray-200 bg-[#F5F5F5] text-[#0A0A0A] font-semibold rounded-lg text-sm hover:shadow-sm"
            >
              {exporting ? "Exporting..." : "Export CSV"}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
