import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { lienReportsService } from "@/lib/liens/lien-reports.service";
import {
  ColumnGroup,
  ReportColumnOption,
  ReportListResponse,
  ReportsResponse,
  ExportReportRequest,
  CreateReports,
  ReportTotals,
  HistoryNoteType,
  CaseHistoryParams,
} from "@/lib/liens/lien-report.types";
import { formatCurrency } from "@/lib/lien-utils";

interface UseCaseNoteHistoryProps {
  type: HistoryNoteType;
  request: CaseHistoryParams;
  initialPage?: number;
  initialPageSize?: number;
}

type SummaryTotals = {
  summaryTotals: ReportTotals;
};

export function useCaseNoteHistory({ request }: UseCaseNoteHistoryProps) {
  return useQuery({
    queryKey: ["caseHistory", request],
    queryFn: () => lienReportsService.getCaseNotesHistory(request),
    enabled: Boolean(request),
    refetchOnWindowFocus: false,
  });
}

async function exportReport(req: any) {
  const item = req?.[0];
  const src = `data:text/${item.export_format};base64,${item.base64}`;
  const link = document.createElement("a");
  link.href = src;
  link.download = item.filename;
  link.click();
  link.remove();
}
export function useCaseNoteHistoryExport() {
  return useMutation({
    mutationFn: ({ request }: UseCaseNoteHistoryProps) =>
      lienReportsService.exportcaseNotesHistory(request),
    onSuccess: (data) => exportReport(data),
  });
}

export function useGetAutoGeneratedReportById(
  request: string,
  query: { page: number; pageSize: 10 },
) {
  // Local state for pagination
  const [pagination, setPagination] = useState({
    page: query.page,
    pageSize: query.pageSize,
  });

  // Handlers to update pagination from your UI components
  const handlePageChange = (newPage: number) => {
    setPagination((prev) => ({ ...prev, page: newPage }));
  };

  const { data, isLoading } = useQuery({
    queryKey: ["autoGeneratedById", request, pagination.page],
    queryFn: () =>
      lienReportsService.getAutoGeneratedReportById(request, {...query, page: pagination.page,}),
    enabled: Boolean(request),
    refetchOnWindowFocus: false,
  });

  return {
    data,
    isLoading,
    pagination,
    setPage: handlePageChange,
  };
}

export function useAutoGeneratedReportList({
  page,
  pageSize,
}: {
  page: number;
  pageSize: number;
}) {
  return useQuery({
    queryKey: ["autoGenerated", page, pageSize],
    queryFn: () =>
      lienReportsService.getAutoGeneratedReport({ page, pageSize }),
    enabled: true,
    refetchOnWindowFocus: false,
  });
}

export function useAutoGeneratedReportExport() {
  return useMutation({
    mutationFn: ({ id }: any) =>
      lienReportsService.exportAutoGeneratedReport(id),
    onSuccess: (data) => exportReport(data),
  });
}
