'use client';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import type { TenantRegistration } from '@/lib/control-center-api';
import { approveRegistration, declineRegistration } from '../actions';

export function DecisionPanel({ application }: { application: TenantRegistration }) {
  const router = useRouter(); const [mode, setMode] = useState<'approve' | 'decline' | null>(null); const [reason, setReason] = useState(''); const [error, setError] = useState(''); const [pending, start] = useTransition();
  const submit = () => { if (!mode) return; start(async () => { try { if (mode === 'approve') await approveRegistration(application.id); else await declineRegistration(application.id, reason); setMode(null); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'The request failed.'); } }); };
  return <>{application.registrationStatus === 'PendingReview' && <div className="flex gap-2"><button onClick={() => setMode('approve')} className="rounded-lg bg-[#16a34a] px-4 py-2 text-sm font-medium text-white">Approve</button><button onClick={() => setMode('decline')} className="rounded-lg border border-[#dc2626] px-4 py-2 text-sm font-medium text-[#dc2626]">Decline</button></div>}{mode && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-[440px] rounded-xl bg-white p-6 shadow-xl"><h2 className="text-lg font-semibold text-[#111827]">{mode === 'approve' ? 'Approve tenant registration?' : 'Decline tenant registration'}</h2><p className="mt-2 text-sm text-[#6b7280]">{mode === 'approve' ? `Approve ${application.tenantName} and begin provisioning?` : 'Provide a reason for declining this application.'}</p>{mode === 'decline' && <textarea autoFocus value={reason} onChange={e => setReason(e.target.value)} rows={3} className="mt-4 w-full rounded-lg border border-[#d1d5db] p-3 text-sm" placeholder="Reason"/>}{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-6 flex justify-end gap-2"><button onClick={() => setMode(null)} className="rounded-lg border border-[#d1d5db] px-4 py-2 text-sm">Cancel</button><button disabled={pending || (mode === 'decline' && !reason.trim())} onClick={submit} className={`rounded-lg px-4 py-2 text-sm font-medium text-white disabled:opacity-50 ${mode === 'approve' ? 'bg-[#16a34a]' : 'bg-[#dc2626]'}`}>{pending ? 'Saving…' : mode === 'approve' ? 'Approve' : 'Decline'}</button></div></div></div>}</>;
}
