// <auto-generated />
using System;
using Intake.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intake.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IntakeDbContext))]
    [Migration("20260813232726_InitialIntakeConfiguration")]
    partial class InitialIntakeConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Intake.Domain.Configuration.ProcessingProfileDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSystemDefined")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ProcessingProfileDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("019b0a9c-3f2d-7a11-9b72-5c8e2f1d4a60"),
                            Code = "LIEN_INTAKE_V1",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Conservative configuration contract for future lien-intake processing.",
                            DisplayName = "Lien Intake V1",
                            IsActive = true,
                            IsSystemDefined = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        });
                });

            modelBuilder.Entity("Intake.Domain.Configuration.TenantIntakeConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AutoProcessingEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ConfigurationVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("DefaultProcessingProfileCode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("RequireHumanReviewByDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultProcessingProfileCode");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantIntakeConfigurations", (string)null);
                });

            modelBuilder.Entity("Intake.Domain.Configuration.TenantProcessingProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ConfigurationVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("DefaultTenantKey")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ProcessingProfileDefinitionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultTenantKey")
                        .IsUnique();

                    b.HasIndex("ProcessingProfileDefinitionId");

                    b.HasIndex("TenantId", "IsDefault");

                    b.HasIndex("TenantId", "IsEnabled");

                    b.HasIndex("TenantId", "ProcessingProfileDefinitionId")
                        .IsUnique();

                    b.ToTable("TenantProcessingProfiles", (string)null);
                });

            modelBuilder.Entity("Intake.Domain.Configuration.TenantProcessingProfile", b =>
                {
                    b.HasOne("Intake.Domain.Configuration.ProcessingProfileDefinition", "ProcessingProfileDefinition")
                        .WithMany("TenantAssignments")
                        .HasForeignKey("ProcessingProfileDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcessingProfileDefinition");
                });

            modelBuilder.Entity("Intake.Domain.Configuration.ProcessingProfileDefinition", b =>
                {
                    b.Navigation("TenantAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
