// <auto-generated />
using System;
using Intake.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intake.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IntakeDbContext))]
    [Migration("20260814004756_AddInboundEmailRepository")]
    partial class AddInboundEmailRepository
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Intake.Domain.Configuration.ProcessingProfileDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSystemDefined")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ProcessingProfileDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("019b0a9c-3f2d-7a11-9b72-5c8e2f1d4a60"),
                            Code = "LIEN_INTAKE_V1",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Conservative configuration contract for future lien-intake processing.",
                            DisplayName = "Lien Intake V1",
                            IsActive = true,
                            IsSystemDefined = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        });
                });

            modelBuilder.Entity("Intake.Domain.Configuration.TenantIntakeConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AutoProcessingEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ConfigurationVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("DefaultProcessingProfileCode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("RequireHumanReviewByDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultProcessingProfileCode");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantIntakeConfigurations", (string)null);
                });

            modelBuilder.Entity("Intake.Domain.Configuration.TenantProcessingProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ConfigurationVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("DefaultTenantKey")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ProcessingProfileDefinitionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultTenantKey")
                        .IsUnique();

                    b.HasIndex("ProcessingProfileDefinitionId");

                    b.HasIndex("TenantId", "IsDefault");

                    b.HasIndex("TenantId", "IsEnabled");

                    b.HasIndex("TenantId", "ProcessingProfileDefinitionId")
                        .IsUnique();

                    b.ToTable("TenantProcessingProfiles", (string)null);
                });

            modelBuilder.Entity("Intake.Domain.Emails.InboundEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AttachmentCount")
                        .HasColumnType("int");

                    b.Property<string>("CaptureStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DuplicateCaptureCount")
                        .HasColumnType("int");

                    b.Property<string>("FromAddress")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("FromDisplayName")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<bool>("HasAttachments")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HtmlBody")
                        .HasColumnType("longtext");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("InReplyToMessageId")
                        .HasMaxLength(768)
                        .HasColumnType("varchar(768)");

                    b.Property<string>("InternetMessageId")
                        .HasMaxLength(768)
                        .HasColumnType("varchar(768)");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProcessingProfileCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset?>("ProviderCreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(768)
                        .HasColumnType("varchar(768)");

                    b.Property<string>("ProviderThreadId")
                        .HasMaxLength(768)
                        .HasColumnType("varchar(768)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RawMessageContent")
                        .HasColumnType("longtext");

                    b.Property<string>("RawMessageHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long?>("RawMessageSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReferencesJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReplyToAddress")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("ReplyToDisplayName")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("SenderAddress")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("SenderDisplayName")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("SourceConfigurationVersion")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(998)
                        .HasColumnType("varchar(998)");

                    b.Property<int?>("TenantConfigurationVersion")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantIntakeSourceId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("TenantProfileConfigurationVersion")
                        .HasColumnType("int");

                    b.Property<string>("TextBody")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TenantIntakeSourceId");

                    b.HasIndex("TenantId", "ReceivedAt");

                    b.HasIndex("TenantId", "CaptureStatus", "ReceivedAt");

                    b.HasIndex("TenantId", "Provider", "ReceivedAt");

                    b.HasIndex("TenantId", "Purpose", "ReceivedAt");

                    b.HasIndex("TenantId", "TenantIntakeSourceId", "ReceivedAt");

                    b.ToTable("InboundEmails", (string)null);
                });

            modelBuilder.Entity("Intake.Domain.Emails.InboundEmailAttachmentMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentDisposition")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContentId")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<Guid>("InboundEmailId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsInline")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<string>("ProviderAttachmentId")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InboundEmailId", "Ordinal");

                    b.ToTable("InboundEmailAttachmentMetadata", (string)null);
                });

            modelBuilder.Entity("Intake.Domain.Emails.InboundEmailRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<Guid>("InboundEmailId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NormalizedEmailAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<string>("RecipientType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("InboundEmailId", "RecipientType");

                    b.ToTable("InboundEmailRecipients", (string)null);
                });

            modelBuilder.Entity("Intake.Domain.Sources.TenantIntakeSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ConfigurationVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<string>("ConnectorConfigurationJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("CredentialReference")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("DefaultTenantPurposeKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LastValidatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastValidationMessage")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("NormalizedEmailAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProcessingProfileCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultTenantPurposeKey")
                        .IsUnique();

                    b.HasIndex("NormalizedEmailAddress")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("NormalizedEmailAddress", "IsActive");

                    b.HasIndex("TenantId", "ProcessingProfileCode");

                    b.HasIndex("TenantId", "Purpose");

                    b.ToTable("TenantIntakeSources", (string)null);
                });

            modelBuilder.Entity("Intake.Domain.Configuration.TenantProcessingProfile", b =>
                {
                    b.HasOne("Intake.Domain.Configuration.ProcessingProfileDefinition", "ProcessingProfileDefinition")
                        .WithMany("TenantAssignments")
                        .HasForeignKey("ProcessingProfileDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcessingProfileDefinition");
                });

            modelBuilder.Entity("Intake.Domain.Emails.InboundEmail", b =>
                {
                    b.HasOne("Intake.Domain.Sources.TenantIntakeSource", null)
                        .WithMany()
                        .HasForeignKey("TenantIntakeSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Intake.Domain.Emails.InboundEmailAttachmentMetadata", b =>
                {
                    b.HasOne("Intake.Domain.Emails.InboundEmail", "InboundEmail")
                        .WithMany("AttachmentMetadata")
                        .HasForeignKey("InboundEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InboundEmail");
                });

            modelBuilder.Entity("Intake.Domain.Emails.InboundEmailRecipient", b =>
                {
                    b.HasOne("Intake.Domain.Emails.InboundEmail", "InboundEmail")
                        .WithMany("Recipients")
                        .HasForeignKey("InboundEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InboundEmail");
                });

            modelBuilder.Entity("Intake.Domain.Configuration.ProcessingProfileDefinition", b =>
                {
                    b.Navigation("TenantAssignments");
                });

            modelBuilder.Entity("Intake.Domain.Emails.InboundEmail", b =>
                {
                    b.Navigation("AttachmentMetadata");

                    b.Navigation("Recipients");
                });
#pragma warning restore 612, 618
        }
    }
}
