using Liens.Domain.Entities;

namespace Liens.Application.Repositories;

public interface IAutoGeneratedReportRepository
{
    Task<(List<AutoGeneratedReport> Items, int TotalCount)> ListAsync(
        Guid tenantId,
        int page,
        int pageSize,
        CancellationToken ct = default);

    Task<AutoGeneratedReport?> GetByIdAsync(
        Guid tenantId,
        long reportId,
        CancellationToken ct = default);

    Task<bool> EnsureExistsAsync(
        AutoGeneratedReport report,
        CancellationToken ct = default);
}
