// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Xenia.Infrastructure.Persistence;

#nullable disable

namespace Xenia.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(XeniaDbContext))]
    [Migration("20260710000006_AddDurableSyncLock")]
    partial class AddDurableSyncLock
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            // Minimal designer — full model in XeniaDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
