// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Xenia.Infrastructure.Persistence;

#nullable disable

namespace Xenia.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(XeniaDbContext))]
    [Migration("20260710000005_AddIngestionEngine")]
    partial class AddIngestionEngine
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
