namespace Liens.Infrastructure.Services;

public interface IAutoGeneratedReportExportStreamFactory
{
    Stream Create();
}

internal sealed class AutoGeneratedReportExportStreamFactory : IAutoGeneratedReportExportStreamFactory
{
    public Stream Create() => AutoGeneratedReportService.CreateExportStream();
}
