using System.Net.Http.Json;
using Liens.Application.Interfaces;

namespace Liens.Infrastructure.Services;

public sealed class TenantServiceAutoGeneratedReportTenantSource : IAutoGeneratedReportTenantSource
{
    private readonly IHttpClientFactory _httpClientFactory;

    public TenantServiceAutoGeneratedReportTenantSource(IHttpClientFactory httpClientFactory)
    {
        _httpClientFactory = httpClientFactory;
    }

    public async Task<IReadOnlyList<Guid>> ListEligibleTenantIdsAsync(CancellationToken ct = default)
    {
        var client = _httpClientFactory.CreateClient("AutoGeneratedReportTenantService");
        using var response = await client.GetAsync(
            "/api/internal/tenants/eligible/synqliens",
            ct);
        response.EnsureSuccessStatusCode();

        var payload = await response.Content.ReadFromJsonAsync<EligibleTenantResponse>(
            cancellationToken: ct);
        return payload?.TenantIds ?? [];
    }

    private sealed class EligibleTenantResponse
    {
        public List<Guid> TenantIds { get; init; } = [];
    }
}
