using Liens.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Migrations.Operations;
using Microsoft.Extensions.DependencyInjection;

namespace Liens.Api.Tests.Infrastructure;

public class LiensMigrationDiscoveryTests
{
    [Fact]
    public void MigrationsAssembly_Contains_HandAuthoredMigrationFixes()
    {
        using var services = BuildServices();
        using var scope = services.CreateScope();
        using var db = scope.ServiceProvider.GetRequiredService<LiensDbContext>();

        var migrationsAssembly = db.GetService<IMigrationsAssembly>();
        var migrationIds = migrationsAssembly.Migrations.Keys.ToHashSet(StringComparer.Ordinal);

        Assert.Contains("20260418200000_AddWorkflowTransitions", migrationIds);
        Assert.Contains("20260420000001_AddTaskGovernanceSettings", migrationIds);
        Assert.Contains("20260420000002_AddTaskFlowLinkage", migrationIds);
        Assert.Contains("20260421000002_DropLiensConfigTables", migrationIds);
        Assert.Contains("20260513000001_SeedLookupValues", migrationIds);
        Assert.Contains("20260625000001_AddLienLegacyMedicalFields", migrationIds);
        Assert.Contains("20260629164601_AddFacilityLinkedContactSubtype", migrationIds);
        Assert.Contains("20260731000001_AddLienPurchaseAndSettlementDates", migrationIds);
        Assert.Contains("20260729163919_SecureSellingBuyerAccessAndAddIdempotencyRecords", migrationIds);
        Assert.Contains("20260729163918_RecordPublicBuyerAccountActivation", migrationIds);
        Assert.Contains("20260809105501_AddSellingCompanyDirectory", migrationIds);
        Assert.Contains("20260809185312_AddSellingPartyCompatibility", migrationIds);
        Assert.Contains("20260813102730_AddAutoGeneratedReports", migrationIds);
        Assert.Contains("20260824190000_AddCasePaymentLedgerFields", migrationIds);
        Assert.Contains("20260825120000_AddWeeklyAgingReportIndex", migrationIds);
        Assert.Contains("20260825160000_AddLegacyReportParityFields", migrationIds);
        Assert.Contains("20260825180000_AddLienImportedCreatedByName", migrationIds);
    }

    [Fact]
    public void HandAuthoredMigrationTypes_AreBoundTo_LiensDbContext()
    {
        var migrationTypes = new[]
        {
            typeof(Liens.Infrastructure.Persistence.Migrations.AddWorkflowTransitions),
            typeof(Liens.Infrastructure.Persistence.Migrations.AddTaskGovernanceSettings),
            typeof(Liens.Infrastructure.Persistence.Migrations.AddTaskFlowLinkage),
            typeof(Liens.Infrastructure.Persistence.Migrations.DropLiensConfigTables),
            typeof(Liens.Infrastructure.Persistence.Migrations.SeedLookupValues),
            typeof(Liens.Infrastructure.Persistence.Migrations.AddLienLegacyMedicalFields),
            typeof(Liens.Infrastructure.Persistence.Migrations.AddFacilityLinkedContactSubtype),
            typeof(Liens.Infrastructure.Persistence.Migrations.AddLienPurchaseAndSettlementDates),
            typeof(Liens.Infrastructure.Persistence.Migrations.SecureSellingBuyerAccessAndAddIdempotencyRecords),
            typeof(Liens.Infrastructure.Persistence.Migrations.RecordPublicBuyerAccountActivation),
            typeof(Liens.Infrastructure.Persistence.Migrations.AddSellingCompanyDirectory),
            typeof(Liens.Infrastructure.Persistence.Migrations.AddSellingPartyCompatibility),
            typeof(Liens.Infrastructure.Persistence.Migrations.AddCasePaymentLedgerFields),
            typeof(Liens.Infrastructure.Persistence.Migrations.AddWeeklyAgingReportIndex),
            typeof(Liens.Infrastructure.Persistence.Migrations.AddLegacyReportParityFields),
            typeof(Liens.Infrastructure.Persistence.Migrations.AddLienImportedCreatedByName),
        };

        foreach (var migrationType in migrationTypes)
        {
            var dbContextAttribute = migrationType.GetCustomAttributes(typeof(DbContextAttribute), inherit: false)
                .Cast<DbContextAttribute>()
                .SingleOrDefault();

            Assert.NotNull(dbContextAttribute);
            Assert.Equal(typeof(LiensDbContext), dbContextAttribute!.ContextType);

            var migrationAttribute = migrationType.GetCustomAttributes(typeof(MigrationAttribute), inherit: false)
                .Cast<MigrationAttribute>()
                .SingleOrDefault();

            Assert.NotNull(migrationAttribute);
            Assert.False(string.IsNullOrWhiteSpace(migrationAttribute!.Id));
        }
    }

    [Fact]
    public void SellingCompanyDirectoryMigration_CanResumeAfterPartialMySqlDdl()
    {
        var migration = new Liens.Infrastructure.Persistence.Migrations.AddSellingCompanyDirectory();
        var sql = AssertOnlyGuardedSqlOperations(migration);

        Assert.Contains("CREATE TABLE IF NOT EXISTS `liens_CompanyTypes`", sql, StringComparison.Ordinal);
        Assert.Contains("CREATE TABLE IF NOT EXISTS `liens_Companies`", sql, StringComparison.Ordinal);
        Assert.Contains("CREATE TABLE IF NOT EXISTS `liens_ContactPersonTypes`", sql, StringComparison.Ordinal);
        Assert.Contains("CREATE TABLE IF NOT EXISTS `liens_CompanyContactPersons`", sql, StringComparison.Ordinal);
        Assert.Contains("INSERT IGNORE INTO `liens_CompanyTypes`", sql, StringComparison.Ordinal);
        Assert.Contains("INSERT IGNORE INTO `liens_ContactPersonTypes`", sql, StringComparison.Ordinal);
        Assert.Contains("information_schema.STATISTICS", sql, StringComparison.Ordinal);
        Assert.Contains("information_schema.TABLE_CONSTRAINTS", sql, StringComparison.Ordinal);
    }

    [Fact]
    public void SellingPartyCompatibilityMigration_CanResumeAfterPartialMySqlDdl()
    {
        var migration = new Liens.Infrastructure.Persistence.Migrations.AddSellingPartyCompatibility();
        var sql = AssertOnlyGuardedSqlOperations(migration);

        Assert.Equal(10, CountOccurrences(sql, "information_schema.COLUMNS"));
        Assert.Contains("CREATE TABLE IF NOT EXISTS `liens_SellingPartyAliases`", sql, StringComparison.Ordinal);
        Assert.Contains("CREATE TABLE IF NOT EXISTS `liens_SellingPartyBackfillCheckpoints`", sql, StringComparison.Ordinal);
        Assert.Contains("CREATE TABLE IF NOT EXISTS `liens_SellingPartyBackfillQuarantines`", sql, StringComparison.Ordinal);
        Assert.Contains("information_schema.STATISTICS", sql, StringComparison.Ordinal);
        Assert.Contains("information_schema.TABLE_CONSTRAINTS", sql, StringComparison.Ordinal);
        Assert.Contains("`FundingCompanyCompanyId` char(36) COLLATE ascii_general_ci NULL", sql, StringComparison.Ordinal);
        Assert.Contains("`HandlingLawFirmCompanyId` char(36) COLLATE ascii_general_ci NULL", sql, StringComparison.Ordinal);
    }

    [Fact]
    public void AutoGeneratedReportsMigration_CanResumeAfterPartialMySqlDdl()
    {
        var migration = new Liens.Infrastructure.Persistence.Migrations.AddAutoGeneratedReports();
        var sql = AssertOnlyGuardedSqlOperations(migration);

        Assert.Contains("CREATE TABLE IF NOT EXISTS `liens_AutoGeneratedReports`", sql, StringComparison.Ordinal);
        Assert.Contains("information_schema.STATISTICS", sql, StringComparison.Ordinal);
        Assert.Contains("IX_AutoGeneratedReports_TenantId_ReportDate_Id", sql, StringComparison.Ordinal);
        Assert.Contains("UX_AutoGeneratedReports_TenantId_ApiPath_ReportDate", sql, StringComparison.Ordinal);
        Assert.Contains("UX_AutoGeneratedReports_TenantId_Code", sql, StringComparison.Ordinal);
    }

    [Fact]
    public void WeeklyAgingReportIndexMigration_CanResumeAfterPartialMySqlDdl()
    {
        var migration = new Liens.Infrastructure.Persistence.Migrations.AddWeeklyAgingReportIndex();
        var sql = AssertOnlyGuardedSqlOperations(migration);

        Assert.Contains("information_schema.STATISTICS", sql, StringComparison.Ordinal);
        Assert.Contains("IX_SellingBuyerAccessLinks_WeeklyAging", sql, StringComparison.Ordinal);
        Assert.Contains("`RespondedAtUtc`, `LienId`", sql, StringComparison.Ordinal);
    }

    [Fact]
    public void LegacyReportParityMigration_CanResumeAfterPartialMySqlDdl()
    {
        var migration = new Liens.Infrastructure.Persistence.Migrations.AddLegacyReportParityFields();
        var sql = AssertOnlyGuardedSqlOperations(migration);

        Assert.Equal(11, CountOccurrences(sql, "information_schema.COLUMNS"));
        Assert.Contains("CREATE TABLE IF NOT EXISTS `liens_LegacyFieldMigrationStates`", sql, StringComparison.Ordinal);
        Assert.Contains("UX_LegacyFieldMigrationStates_Source_FieldGroup", sql, StringComparison.Ordinal);
        Assert.Contains("FK_Cases_AttorneyContactPerson", sql, StringComparison.Ordinal);
        Assert.Contains("information_schema.TABLE_CONSTRAINTS", sql, StringComparison.Ordinal);
    }

    [Fact]
    public void AutoGeneratedReportSchemaRecovery_ReplaysGuardedMigration()
    {
        var migration = Liens.Infrastructure.Persistence.Migrations
            .AutoGeneratedReportSchemaRepair.CreateRecoveryMigration();

        Assert.IsType<Liens.Infrastructure.Persistence.Migrations.AddAutoGeneratedReports>(migration);
        AssertOnlyGuardedSqlOperations(migration);
    }

    [Fact]
    public void LiensConnectionString_EnablesUserVariablesForGuardedMySqlDdl()
    {
        var configured = LiensMySqlConnectionString.Configure(
            "Server=127.0.0.1;Database=liens;User=root;Password=ignored;");
        var builder = new MySqlConnector.MySqlConnectionStringBuilder(configured);

        Assert.True(builder.AllowUserVariables);
    }

    private static string AssertOnlyGuardedSqlOperations(Migration migration)
    {
        Assert.NotEmpty(migration.UpOperations);
        Assert.All(migration.UpOperations, operation => Assert.IsType<SqlOperation>(operation));

        var sqlOperations = migration.UpOperations.Cast<SqlOperation>().ToList();
        Assert.All(sqlOperations, operation => Assert.True(operation.SuppressTransaction));
        Assert.All(sqlOperations, operation => Assert.EndsWith(";", operation.Sql.TrimEnd(), StringComparison.Ordinal));

        return string.Join(Environment.NewLine, sqlOperations.Select(operation => operation.Sql));
    }

    private static int CountOccurrences(string value, string search)
    {
        var count = 0;
        var index = 0;
        while ((index = value.IndexOf(search, index, StringComparison.Ordinal)) >= 0)
        {
            count++;
            index += search.Length;
        }

        return count;
    }

    private static ServiceProvider BuildServices()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddDbContext<LiensDbContext>(options =>
            options.UseMySql(
                "Server=127.0.0.1;Port=3306;Database=discovery_only;User=root;Password=ignored;",
                new MySqlServerVersion(new Version(8, 0, 0))));

        return services.BuildServiceProvider();
    }
}
