// <auto-generated />
using CareConnect.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CareConnect.Infrastructure.Data.Migrations
{
    partial class AddDateOfAccidentToReferral
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
