using Liens.Application.Interfaces;
using Liens.Infrastructure.Options;
using Microsoft.Extensions.Options;

namespace Liens.Api.HostedServices;

internal sealed class WeeklyAutoGeneratedReportHostedService(
    IServiceScopeFactory scopeFactory,
    IOptions<AutoGeneratedReportOptions> options,
    TimeProvider timeProvider,
    ILogger<WeeklyAutoGeneratedReportHostedService> logger) : BackgroundService
{
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        var settings = options.Value;
        if (!settings.SchedulerEnabled)
        {
            logger.LogInformation("Auto-generated report scheduler is disabled.");
            return;
        }

        TimeZoneInfo pacificTimeZone;
        try
        {
            pacificTimeZone = ResolvePacificTimeZone();
        }
        catch (Exception ex) when (ex is TimeZoneNotFoundException or InvalidTimeZoneException)
        {
            logger.LogCritical(ex, "Pacific timezone is unavailable; scheduler cannot start.");
            return;
        }

        var reconciliationInterval = TimeSpan.FromMinutes(
            Math.Clamp(settings.ReconciliationIntervalMinutes, 1, 24 * 60));

        while (!stoppingToken.IsCancellationRequested)
        {
            await ReconcileLatestDueAsync(pacificTimeZone, stoppingToken);

            var nowUtc = timeProvider.GetUtcNow();
            var nextOccurrence = GetNextOccurrence(nowUtc, pacificTimeZone);
            var untilNextOccurrence = nextOccurrence - nowUtc;
            var delay = untilNextOccurrence > TimeSpan.Zero && untilNextOccurrence < reconciliationInterval
                ? untilNextOccurrence
                : reconciliationInterval;

            try
            {
                await Task.Delay(delay, timeProvider, stoppingToken);
            }
            catch (OperationCanceledException) when (stoppingToken.IsCancellationRequested)
            {
                break;
            }
        }
    }

    private async Task ReconcileLatestDueAsync(
        TimeZoneInfo pacificTimeZone,
        CancellationToken ct)
    {
        var reportDate = GetLatestDueReportDate(timeProvider.GetUtcNow(), pacificTimeZone);

        try
        {
            using var scope = scopeFactory.CreateScope();
            var service = scope.ServiceProvider.GetRequiredService<IAutoGeneratedReportService>();
            var result = await service.ReconcileWeeklyBccAsync(reportDate, ct);

            logger.LogInformation(
                "Weekly BCC metadata reconciliation for {ReportDate}: eligible {EligibleCount}, inserted {InsertedCount}, existing {ExistingCount}, failed {FailedCount}.",
                result.ReportDate,
                result.EligibleTenantCount,
                result.InsertedCount,
                result.ExistingCount,
                result.FailedCount);
        }
        catch (OperationCanceledException) when (ct.IsCancellationRequested)
        {
            throw;
        }
        catch (Exception ex)
        {
            logger.LogError(
                ex,
                "Weekly BCC metadata reconciliation failed for {ReportDate}; the next reconciliation will retry.",
                reportDate);
        }
    }

    internal static TimeZoneInfo ResolvePacificTimeZone()
    {
        try
        {
            return TimeZoneInfo.FindSystemTimeZoneById("America/Los_Angeles");
        }
        catch (TimeZoneNotFoundException)
        {
            return TimeZoneInfo.FindSystemTimeZoneById("Pacific Standard Time");
        }
    }

    internal static DateOnly GetLatestDueReportDate(
        DateTimeOffset utcNow,
        TimeZoneInfo pacificTimeZone)
    {
        var localNow = TimeZoneInfo.ConvertTime(utcNow, pacificTimeZone);
        var daysSinceFriday = ((int)localNow.DayOfWeek - (int)DayOfWeek.Friday + 7) % 7;
        var localOccurrence = localNow.Date.AddDays(-daysSinceFriday).AddHours(4);
        if (localNow.DateTime < localOccurrence)
            localOccurrence = localOccurrence.AddDays(-7);

        return DateOnly.FromDateTime(localOccurrence);
    }

    internal static DateTimeOffset GetNextOccurrence(
        DateTimeOffset utcNow,
        TimeZoneInfo pacificTimeZone)
    {
        var latestDate = GetLatestDueReportDate(utcNow, pacificTimeZone);
        var nextLocal = latestDate.ToDateTime(new TimeOnly(4, 0)).AddDays(7);
        var nextUtc = TimeZoneInfo.ConvertTimeToUtc(
            DateTime.SpecifyKind(nextLocal, DateTimeKind.Unspecified),
            pacificTimeZone);
        return new DateTimeOffset(nextUtc, TimeSpan.Zero);
    }
}
