using BuildingBlocks.Authorization;
using BuildingBlocks.Authorization.Filters;
using BuildingBlocks.Context;
using Liens.Application.DTOs;
using Liens.Application.Interfaces;
using Liens.Domain;

namespace Liens.Api.Endpoints;

public static class AutoGeneratedReportEndpoints
{
    private const int DefaultPageSize = 50;
    private const int MaximumPageSize = 100;

    public static void MapAutoGeneratedReportEndpoints(this WebApplication app)
    {
        var canonical = app.MapGroup("/api/liens/reports/auto-generated")
            .RequireAuthorization(Policies.AuthenticatedUser)
            .RequireProductAccess(LiensPermissions.ProductCode);
        MapRoutes(canonical);

        var legacy = app.MapGroup("/report/auto-generated")
            .RequireAuthorization(Policies.AuthenticatedUser)
            .RequireProductAccess(LiensPermissions.ProductCode);
        MapRoutes(legacy);
    }

    private static void MapRoutes(RouteGroupBuilder group)
    {
        group.MapGet(string.Empty, ListReports)
            .RequirePermission(LiensPermissions.CaseRead);
        group.MapPost("/{reportId:long}/execute", ExecuteReport)
            .RequirePermission(LiensPermissions.CaseRead);
        group.MapPost("/{reportId:long}/export", ExportReport)
            .RequirePermission(LiensPermissions.CaseRead);
    }

    private static async Task<IResult> ListReports(
        IAutoGeneratedReportService service,
        ICurrentRequestContext context,
        HttpContext httpContext,
        CancellationToken ct,
        int page = 1,
        int pageSize = DefaultPageSize)
    {
        httpContext.Response.Headers.CacheControl = "no-store";
        if (page < 1 || pageSize < 1 || pageSize > MaximumPageSize)
        {
            return Results.BadRequest(new
            {
                isSuccess = false,
                message = $"page must be at least 1 and pageSize must be between 1 and {MaximumPageSize}.",
            });
        }

        var tenantId = CaseEndpoints.RequireTenantId(context);
        var result = await service.ListAsync(tenantId, page, pageSize, ct);
        return Results.Ok(new
        {
            isSuccess = true,
            message = "Auto-generated reports retrieved.",
            result.Page,
            result.PageSize,
            result.TotalCount,
            data = result.Items,
        });
    }

    private static async Task<IResult> ExecuteReport(
        long reportId,
        IAutoGeneratedReportService service,
        ICurrentRequestContext context,
        HttpContext httpContext,
        CancellationToken ct,
        int page = 1,
        int pageSize = DefaultPageSize)
    {
        httpContext.Response.Headers.CacheControl = "no-store";
        if (page < 1 || pageSize < 1 || pageSize > MaximumPageSize)
        {
            return Results.BadRequest(new
            {
                isSuccess = false,
                message = $"page must be at least 1 and pageSize must be between 1 and {MaximumPageSize}.",
            });
        }

        var tenantId = CaseEndpoints.RequireTenantId(context);
        var result = await service.ExecuteAsync(tenantId, reportId, page, pageSize, ct);

        if (result.Status == AutoGeneratedReportExecutionStatus.NotFound)
        {
            return Results.NotFound(new
            {
                isSuccess = false,
                message = "Auto-generated report not found.",
            });
        }

        if (result.Status == AutoGeneratedReportExecutionStatus.UnsupportedPath)
        {
            return Results.Conflict(new
            {
                isSuccess = false,
                message = "The saved report type is not supported.",
            });
        }

        var weeklyBcc = result.WeeklyBcc!;
        var definition = result.Definition!;
        var totalPages = weeklyBcc.TotalCount == 0
            ? 0
            : ((weeklyBcc.TotalCount - 1) / weeklyBcc.PageSize) + 1;
        return Results.Ok(new
        {
            isSuccess = true,
            message = "Weekly BCC report generated.",
            report = result.Report,
            definition.ReportType,
            definition.SchemaVersion,
            asOfDate = weeklyBcc.AsOfDate,
            weeklyBcc.Page,
            weeklyBcc.PageSize,
            totalPages,
            weeklyBcc.TotalCount,
            definition.Columns,
            data = weeklyBcc.Items,
        });
    }

    private static async Task<IResult> ExportReport(
        long reportId,
        IAutoGeneratedReportService service,
        ICurrentRequestContext context,
        HttpContext httpContext,
        CancellationToken ct)
    {
        httpContext.Response.Headers.CacheControl = "no-store";
        var tenantId = CaseEndpoints.RequireTenantId(context);
        var result = await service.ExportAsync(tenantId, reportId, ct);

        if (result.Status == AutoGeneratedReportExecutionStatus.NotFound)
        {
            return Results.NotFound(new
            {
                isSuccess = false,
                message = "Auto-generated report not found.",
            });
        }

        if (result.Status == AutoGeneratedReportExecutionStatus.UnsupportedPath)
        {
            return Results.Conflict(new
            {
                isSuccess = false,
                message = "The saved report type is not supported.",
            });
        }

        if (result.SizeLimitExceeded)
        {
            return Results.BadRequest(new
            {
                isSuccess = false,
                message = "Export exceeds the 10 MiB file size limit.",
                error = new { code = "validation_error" },
            });
        }

        var report = result.Report!;
        var filename = $"weekly_bcc_{report.Date:yyyyMMdd}.csv";
        return Results.Ok(new
        {
            isSuccess = true,
            message = "CSV generated successfully.",
            data = new object[]
            {
                new
                {
                    base64 = Convert.ToBase64String(result.Content ?? []),
                    filename,
                    export_format = "csv",
                },
            },
        });
    }
}
