"use client";

import { useCallback, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";

import {
  useAutoGeneratedReportExport,
  useGetAutoGeneratedReportById,
} from "@/hooks/use-casenote-history";
import AutoGeneratedReportDisplay from "../../components/auto-generated-report-display";
import { formatCurrency } from "@/lib/lien-utils";
import { NoteCell } from "../../components/note-cell";

export default function ReportDetailsPage() {
  const { id } = useParams();
  const router = useRouter();

  const { data, isLoading, setPage, pagination } =
    useGetAutoGeneratedReportById(id?.toString() ?? "", {
      page: 1,
      pageSize: 10,
    });
  const { mutate: exportHistory, isPending: exporting } =
    useAutoGeneratedReportExport();

  
const columns = data?.columns
  ?.map((item: any) => {
    const isCurrencyField =
      /amt|amount|price|cost|fee|total|reduction|roi|profit/i.test(item.key);

    const isNoteField = item.key.toLowerCase().includes("note") || item.key.toLowerCase().includes("activity");

    const isDefaultMinWidth =
      item.key.includes("facility") ||
      item.key.includes("law") ||
      item.key.includes("case_type")
        ? { minWidth: "220px", width: "100%" }
        : isNoteField
          ? { minWidth: "300px" }
          : item.key.includes("id") || item.key.includes("status")
            ? { minWidth: "135px", width: "100%" }
            : { minWidth: "50px" };

    return {
      id: item.key,
      header: item.label,
      accessorFn: (row: any) => row[item.key],

      meta: {
        ...isDefaultMinWidth,
      },

      cell: ({ row }: any) => {
        const value = row.original[item.key];

        // Handle note fields
        if (isNoteField) {
          return <NoteCell maxLength={60} value={value} />;
        }

        let formattedValue = value;

        // Handle currency fields
        if (isCurrencyField && value !== null && value !== undefined) {
          const cleanString = String(value).replace(/[^0-9.-]+/g, "");
          const numericValue = parseFloat(cleanString);

          if (!isNaN(numericValue)) {
            formattedValue = formatCurrency(numericValue);
          }
        }

        return (
          <span className="text-sm text-gray-700 whitespace-nowrap">
            {formattedValue}
          </span>
        );
      },
    };
  })
  .sort((a: any, b: any) => a.index - b.index);

  useEffect(() => {}, [data]);

  return (
    <>
      <AutoGeneratedReportDisplay
        columns={columns}
        loadingData={isLoading}
        report={{ ...data, ...pagination }}
        onBack={() => router.back()}
        onPaginate={(e) => setPage(e.page)}
        onExport={() => {
          exportHistory({
            id: id,
          });
        }}
      />
      <button
        onClick={() => router.back()}
        className="text-primary text-sm"
      >
        Back to Reports
      </button>
    </>
  );
}
