"use client";

import { useCallback, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";

import {
  useAutoGeneratedReportExport,
  useGetAutoGeneratedReportById,
} from "@/hooks/use-casenote-history";
import AutoGeneratedReportDisplay from "../../components/auto-generated-report-display";
import { formatCurrency } from "@/lib/lien-utils";

export default function ReportDetailsPage() {
  const { id } = useParams();
  const router = useRouter();

  const { data, isLoading, handlePageChange, pagination } =
    useGetAutoGeneratedReportById(id?.toString() ?? "", {
      page: 1,
      pageSize: 10,
    });
  const { mutate: exportHistory, isPending: exporting } =
    useAutoGeneratedReportExport();

  const columns = data?.columns
    ?.map((item: any) => {
      const isCurrencyField =
        /amt|amount|price|cost|fee|total|reduction|roi|profit/i.test(item.key);

      const isDefaultMinWidth =
        item.key.includes("facility") ||
        item.key.includes("law") ||
        item.key.includes("case_type")
          ? { minWidth: "220px", width: "100%" }
          : item.key.toLowerCase().includes("note")
            ? { minWidth: "550px" }
            : item.key.includes("id") || item.key.includes("status")
              ? { minWidth: "135px", width: "100%" }
              : { minWidth: "50px" };
      return {
        id: item.key,
        header: item.label,
        accessorFn: (row: any) => row[item.key],
        meta: {
          ...isDefaultMinWidth,
        },

        cell: ({ row }: any) => {
          const value = row.original[item.key];
          let formattedValue = value;

          if (isCurrencyField && value !== null && value !== undefined) {
            // Remove everything except numbers, periods, and minus signs
            const cleanString = String(value).replace(/[^0-9.-]+/g, "");
            const numericValue = parseFloat(cleanString);

            // Format if it successfully parsed into a valid number
            if (!isNaN(numericValue)) {
              formattedValue = formatCurrency(numericValue);
            }
          }

          return (
            <span className="text-sm text-gray-700">{formattedValue}</span>
          );
        },
      };
    })
    .sort((a: any, b: any) => a.index - b.index);

  useEffect(() => {}, [data]);

  return (
    <>
      <AutoGeneratedReportDisplay
        columns={columns}
        loadingData={isLoading}
        report={{ ...data, ...pagination }}
        onBack={() => router.push("/lien/reports/auto-generated")}
        onPaginate={(e) => handlePageChange}
        onExport={() => {
          console.log("hehehe");
          exportHistory({
            id: id,
          });
        }}
      />
      <button
        onClick={() => router.push("/lien/reports/auto-generated")}
        className="text-primary text-sm"
      >
        Back to Reports
      </button>
    </>
  );
}
